#pragma once

#include "Common.h"

FIRERENDER_NAMESPACE_BEGIN

enum IESLightParameter : ParamID
{
	IES_PARAM_P0 = 101,
	IES_PARAM_P1 = 102,
	IES_PARAM_ENABLED,
	IES_PARAM_AREA_WIDTH,
	IES_PARAM_TARGETED,
	IES_PARAM_INTENSITY
};

FIRERENDER_NAMESPACE_END
