#pragma once

#include "Common.h"

FIRERENDER_NAMESPACE_BEGIN

enum IESLightColorMode
{
	IES_LIGHT_COLOR_MODE_COLOR,
	IES_LIGHT_COLOR_MODE_TEMPERATURE
};

enum IESLightParameter : ParamID
{
	IES_PARAM_P0 = 101,
	IES_PARAM_P1,
	IES_PARAM_ENABLED,
	IES_PARAM_PROFILE,
	IES_PARAM_AREA_WIDTH,
	IES_PARAM_TARGETED,
	IES_PARAM_TARGET_DISTANCE,
	IES_PARAM_INTENSITY,
	IES_PARAM_COLOR_MODE,
	IES_PARAM_COLOR,
	IES_PARAM_TEMPERATURE,
	IES_PARAM_SHADOWS_ENABLED,
	IES_PARAM_SHADOWS_SOFTNESS,
	IES_PARAM_SHADOWS_TRANSPARENCY,
	IES_PARAM_VOLUME_SCALE
};

FIRERENDER_NAMESPACE_END
