#pragma once

#include "FireRenderMtlBase.h"

FIRERENDER_NAMESPACE_BEGIN;

enum InputLUMtl_ParamID : ParamID {
	InputLUMtl_VALUE = 1000
};

BEGIN_DECLARE_FRTEXCLASSDESC(InputLUMtl, L"RPR Input Lookup", FIRERENDER_INPUTLUMTL_CID)
END_DECLARE_FRTEXCLASSDESC()

BEGIN_DECLARE_FRTEX(InputLUMtl)
END_DECLARE_FRTEX(InputLUMtl)


FIRERENDER_NAMESPACE_END;
