/**********************************************************************
Copyright 2020 Advanced Micro Devices, Inc
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
********************************************************************/


//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FireMax.rc
//
#define IDS_PBDESC                      101
#define IDD_FORMVIEW                    101
#define IDD_FIRERENDER_WARNING          101
#define IDS_OSL_MTL                     102
#define IDD_FIRERENDER_DIFFUSEMTL       102
#define IDD_RENDER_SETTINGS             103
#define IDS_OSL_FILETYPES               103
#define IDD_RENDER_CAMERASETTINGS       103
#define IDD_OSL_MTL                     104
#define IDS_FIRERENDER_MTL              104
#define IDD_FIRERENDER_MTL              105
#define IDS_FR_MTL_DIFFUSE              105
#define IDD_RENDER_SETTINGS1            106
#define IDD_AUTOTESTER                  106
#define IDD_AUTOTESTING                 106
#define IDS_FR_MTL_BLEND                106
#define IDD_FIRERENDER_BLENDMTL         107
#define IDS_FR_MTL_BLEND_MATERIAL1      107
#define IDS_FR_MTL_BLEND_MATERIAL2      108
#define IDD_FIRERENDER_ADDMTL           108
#define IDS_FR_MTL_ADD                  109
#define IDD_FIRERENDER_MICROFACETMTL    109
#define IDS_FR_MTL_MICROFACET           110
#define IDD_FIRERENDER_REFLECTIONMTL    110
#define IDS_FR_MTL_REFLECTION           111
#define IDD_FIRERENDER_ARITHMMTL        111
#define IDS_FR_MTL_ARITHM               112
#define IDD_FIRERENDER_INPUTLUMTL       112
#define IDS_ARITHM_OP_0                 113
#define IDD_FIRERENDER_BLENDVALUEMTL    113
#define IDS_ARITHM_OP_1                 114
#define IDD_FIRERENDER_REFRACTIONMTL    114
#define IDS_ARITHM_OP_2                 115
#define IDD_FIRERENDER_MFREFRACTIONMTL  115
#define IDS_ARITHM_OP_3                 116
#define IDD_FIRERENDER_TRANSPARENTMTL   116
#define IDS_ARITHM_OP_4                 117
#define IDD_FIRERENDER_WARDMTL          117
#define IDS_ARITHM_OP_5                 118
#define IDD_FIRERENDER_EMISSIVEMTL      118
#define IDS_ARITHM_OP_6                 119
#define IDD_FIRERENDER_FRESNELMTL       119
#define IDS_ARITHM_OP_7                 120
#define IDD_FIRERENDER_STANDARDMTL      120
#define IDS_ARITHM_OP_8                 121
#define IDD_FIRERENDER_COLORMTL         121
#define IDS_ARITHM_OP_9                 122
#define IDD_FIRERENDER_ORENNAYARMTL     122
#define IDS_ARITHM_OP_10                123
#define IDD_ADVANCED_RENDER_SETTINGS    123
#define IDD_RENDER_ADVANCEDSETTINGS     123
#define IDS_ARITHM_OP_11                124
#define IDD_TEMP_KEEP_DIALOG            124
#define IDS_FR_MTL_INPUTLU              125
#define IDD_FIRERENDER_FRESNELMTL2      125
#define IDS_INPUTLU_VALUE_0             126
#define IDS_INPUTLU_VALUE_1             127
#define IDS_INPUTLU_VALUE_2             128
#define IDS_INPUTLU_VALUE_3             129
#define IDS_INPUTLU_VALUE_4             130
#define IDS_FR_MTL_BLENDVALUE           131
#define IDS_FR_MTL_REFRACTION           132
#define IDS_FR_MTL_MFREFRACTION         133
#define IDS_FR_MTL_TRANSPARENT          134
#define IDS_FR_MTL_WARD                 135
#define IDS_FR_MTL_EMISSIVE             136
#define IDD_FIRERENDER_ENVIRONMENT      136
#define IDS_FR_MTL_MTL                  137
#define IDS_FR_MTL_FRESNEL              137
#define IDS_FR_MTL_STANDARD             138
#define IDS_FR_MTL_COLOR                139
#define IDS_FR_MTLAVG                   140
#define IDS_FR_MTL_ORENNAYAR            141
#define IDS_CASTSHADOWSTTP              142
#define IDD_RENDERLOOP                  143
#define IDS_FR_MTL_FRESNELSCHLICK       143
#define IDD_FIRERENDER_FRESNELSCHLICKMTL 144
#define IDS_FR_MTL_DISPLACEMENT         144
#define IDD_FIRERENDER_DISPLACEMENTMTL  145
#define IDS_FR_MTL_NORMAL               145
#define IDD_FIRERENDER_NORMALMTL        146
#define IDS_FR_MTL_BUMP                 146
#define IDS_FR_MTL_DIFFUSEREFRACTION    146
#define IDD_FIRERENDER_DIFFUSEREFRACTIONMTL 147
#define IDS_FR_ACTION_PAN               147
#define IDS_FR_ACTION_TABLE             148
#define IDD_FIRERENDER_MATERIALMTL      148
#define FR_ACTION_ORBIT                 149
#define IDS_FR_ACTION_ORBIT             149
#define IDS_FR_ACTION_ZOOM              150
#define IDD_TEMP                        150
#define IDS_FR_MTL_MATERIAL             151
#define IDD_FIRERENDER_UBERMTL          151
#define IDS_FR_MTL_MATERIAL_SURFACE     152
#define IDS_FR_MTL_MATERIAL_VOLUME      153
#define IDS_FR_MTL_MATERIAL_DISPLACEMENT 154
#define IDS_FR_MTL_SHADOWCATCHER        155
#define IDS_FR_MTL_UBER                 156
#define IDS_FR_ENVIRONMENT_ACTIVE_TTP   157
#define IDS_ARITHM_OP_FLOOR             158
#define IDS_ARITHM_OP_MAGNITUDE         159
#define IDS_ARITHM_OP_NORMALIZE         160
#define IDS_ARITHM_OP_ABS               161
#define IDS_ARITHM_OP_MIN               162
#define IDS_ARITHM_OP_MAX               163
#define IDS_ARITHM_OP_MOD               164
#define IDS_ARITHM_OP_ASIN              165
#define IDS_ARITHM_OP_ACOS              166
#define IDS_ARITHM_OP_ATAN              167
#define IDS_ARITHM_OP_CROSS             168
#define IDS_ARITHM_OP_CMPAVG            169
#define IDS_ARITHM_OP_AVG               170
#define IDS_FR_ENV                      171
#define IDS_FR_ENVIRONMENT_RADIUS_TTP   172
#define IDD_FIRERENDER_VOLUMEMTL        172
#define IDS_FR_ENVIRONMENT_MAP_TTP      173
#define IDD_RENDER_HWSETTINGS           173
#define IDS_FR_ENVIRONMENT_INTENSITY_TTP 174
#define IDD_RENDER_GENERALSETTINGS      174
#define IDS_FR_ENVIRONMENT_GROUND_HEIGHT_TTP 175
#define IDD_RENDER_TONEMAPPING          175
#define IDS_FR_ENVIRONMENT_SHADOWS_TTP  176
#define IDD_RENDER_BG                   176
#define IDS_FR_ENVIRONMENT_REFLECTION_TRANSPARENCY_TTP 177
#define IDS_FR_ENVIRONMENT_REFLECTION_STRENGTH_TTP 177
#define IDS_FR_ENVIRONMENT_REFLECTIONS_TTP 178
#define IDS_FR_ENVIRONMENT_REFLECTIONS_COLOR_TTP 179
#define IDS_FR_ENVIRONMENT_REFLECTIONS_ROUGHNESS_TTP 180
#define IDB_WORLDMAP                    180
#define IDS_FR_ENVIRONMENT_TYPE_TTP     181
#define IDD_LOCATIONPICKER              181
#define IDS_FR_ENVIRONMENT_SUN_AZYMUTH_TTP 182
#define IDS_FR_ENVIRONMENT_SUN_ALTITUDE_TTP 183
#define IDD_CITYSEARCH                  183
#define IDS_FR_ENVIRONMENT_SKY_ALBEDO_TTP 184
#define IDS_FR_ENVIRONMENT_SKY_TURBIDITY_TTP 185
#define IDD_FIRERENDER_ANALYTICALSUN    185
#define IDS_ENABLED                     186
#define IDD_FIRERENDER_PORTALLIGHT      186
#define IDS_FILTER_ON                   187
#define IDD_XMLMATERIALEXPORTER         187
#define IDS_ELEMENT_NAME                188
#define IDD_RENDER_AASETTINGS           188
#define IDS_BITMAP                      189
#define IDS_RENDER_ELEMENT_OPACITY      190
#define IDD_ABOUT                       190
#define IDS_RENDER_ELEMENT_WORLD_COORDINATE 191
#define IDD_RENDER_SCRIPTS              191
#define IDS_RENDER_ELEMENT_UV           192
#define IDR_RTF_ABOUT                   192
#define IDD_RENDER_QUALITYSETTINGS      192
#define IDS_RENDER_ELEMENT_MATERIAL_IDX 193
#define IDD_DIALOG1                     193
#define IDS_RENDER_ELEMENT_GEOMETRIC_NORMAL 194
#define IDS_RENDER_ELEMENT_SHADING_NORMAL 195
#define IDS_RENDER_ELEMENT_OPACITY_NAME 196
#define IDD_FIRERENDER_IES_LIGHT_GENERAL 197
#define IDS_RENDER_ELEMENT_OPACITY_TYPE_NAME 197
#define IDS_RENDER_ELEMENT_WORLD_COORDINATE_NAME 198
#define IDS_RENDER_ELEMENT_WORLD_COORDINATE_TYPE_NAME 199
#define IDD_FIRERENDER_IES_LIGHT_INTENSITY 199
#define IDS_RENDER_ELEMENT_UV_NAME      200
#define IDS_RENDER_ELEMENT_UV_TYPE_NAME 201
#define IDS_RENDER_ELEMENT_MATERIAL_IDX_NAME 202
#define IDS_RENDER_ELEMENT_MATERIAL_IDX_TYPE_NAME 203
#define IDS_RENDER_ELEMENT_GEOMETRIC_NORMAL_NAME 204
#define IDS_RENDER_ELEMENT_GEOMETRIC_NORMAL_TYPE_NAME 205
#define IDS_RENDER_ELEMENT_SHADING_NORMAL_NAME 206
#define IDD_FIRERENDER_PBRMTL           206
#define IDS_RENDER_ELEMENT_SHADING_NORMAL_TYPE_NAME 207
#define IDS_FR_BACKGROUND_MAP_TTP       208
#define IDS_FR_BACKGROUND_TTP           209
#define IDS_RENDER_ELEMENT_DEPTH        210
#define IDS_RENDER_ELEMENT_DEPTH_NAME   211
#define IDS_RENDER_ELEMENT_DEPTH_TYPE_NAME 212
#define IDS_RENDER_ELEMENT_OBJECT_ID    213
#define IDS_RENDER_ELEMENT_OBJECT_ID_NAME 214
#define IDS_RENDER_ELEMENT_OBJECT_ID_TYPE_NAME 215
#define IDS_FR_MTL_VOLUME               216
#define IDS_FR_MTL_VOLUME_PHASE_TTP     217
#define IDS_FR_MTL_VOLUME_MULTISCATTER_TTP 218
#define IDS_FR_MTL_VOLUME_SCATTERING_MULTIPLIER_TTP 219
#define IDS_FR_MTL_VOLUME_SCATTERING_COLOR_TTP 220
#define IDS_FR_MTL_VOLUME_ABSORPTION_MULTIPLIER_TTP 221
#define IDS_FR_MTL_VOLUME_ABSORPTION_COLOR_TTP 222
#define IDS_PORTAL                      223
#define IDS_FR_PORTAL_TTP               224
#define IDS_SKYELEVATIONTTP             225
#define IDS_STRING226                   226
#define IDD_DIALOG2                     226
#define IDS_STRING227                   227
#define IDS_STRING228                   228
#define IDS_STRING229                   229
#define IDS_STRING230                   230
#define IDS_STRING231                   231
#define IDS_STRING232                   232
#define IDS_STRING233                   233
#define IDS_STRING234                   234
#define IDS_STRING235                   235
#define IDS_STRING236                   236
#define IDS_STRING237                   237
#define IDS_STRING238                   238
#define IDS_STRING239                   239
#define IDS_STRING240                   240
#define IDS_STRING241                   241
#define IDS_STRING242                   242
#define IDS_STRING243                   243
#define IDS_STRING244                   244
#define IDS_STRING245                   245
#define IDS_STRING246                   246
#define IDS_STRING247                   247
#define IDS_STRING248                   248
#define IDS_STRING249                   249
#define IDS_STRING250                   250
#define IDS_STRING251                   251
#define IDS_STRING252                   252
#define IDS_STRING253                   253
#define IDS_STRING254                   254
#define IDS_STRING255                   255
#define IDS_STRING256                   256
#define IDS_STRING257                   257
#define IDS_STRING258                   258
#define IDS_STRING259                   259
#define IDS_STRING260                   260
#define IDS_STRING261                   261
#define IDS_STRING262                   262
#define IDS_STRING263                   263
#define IDS_STRING264                   264
#define IDS_STRING265                   265
#define IDS_STRING266                   266
#define IDS_STRING267                   267
#define IDS_SUBDIV_BOUNDARY_INTEROP_EDGE 268
#define IDS_SUBDIV_BOUNDARY_INTEROP_EDGE_AND_CORNER 269
#define IDS_FR_MTL_UBERV2               270
#define IDS_IOR                         271
#define IDS_STRING272                   272
#define IDS_METALNESS                   272
#define IDS_STRING273                   273
#define IDS_FR_MTL_PBR                  273
#define IDS_MTL_UBERV2_DIFFUSE          274
#define IDS_MTL_UBERV2_BASIC_PARAMS     274
#define IDS_MTL_UBERV2_BASIC            274
#define IDS_MTL_UBERV2_Z                275
#define IDS_MTL_UBERV2_SSS              275
#define IDS_MTL_UBERV2_ABSORPTION       276
#define IDS_MTL_UBERV2_EMISSIVE         277
#define IDS_MTL_UBERV2_OVERALL          278
#define IDS_MTL_UBERV2_COATING          279
#define IDS_MTL_UBER2_LINK_TTP          280
#define IDS_FR_MTL_SC                   300
#define IDD_RENDER_DENOISER             301
#define IDD_FIRERENDER_EXPORT           309
#define IDS_STRING400                   400
#define IDS_STRING401                   401
#define IDS_STRING402                   402
#define IDS_STRING403                   403
#define IDS_PHYS_LIGHT_TYPE_AREA        404
#define IDS_PHYS_LIGHT_TYPE_SPOT        405
#define IDS_PHYS_LIGHT_TYPE_POINT       406
#define IDS_PHYS_LIGHT_TYPE_DIRECTIONAL 407
#define IDS_PHYS_LIGHT_UNITS_LUMINANCE  408
#define IDS_PHYS_LIGHT_UNITS_WATTS      409
#define IDS_PHYS_LIGHT_UNITS_RADIANCE   410
#define IDS_PHYS_LIGHT_MODE_COLOUR      411
#define IDS_PHYS_LIGHT_MODE_TEMPERAT    412
#define IDS_PHYS_LIGHT_SHAPE_DISC       413
#define IDS_PHYS_LIGHT_SHAPE_CYLINDER   414
#define IDS_PHYS_LIGHT_SHAPE_SPHERE     415
#define IDS_PHYS_LIGHT_SHAPE_RECT       416
#define IDS_PHYS_LIGHT_SHAPE_MESH       417
#define IDS_PHYS_LIGHT_DECAY_TYPE_NONE  418
#define IDS_PHYS_LIGHT_DECAY_TYPE_INV   419
#define IDS_PHYS_LIGHT_DECAY_TYPE_LIN   420
#define IDS_PHYS_LIGHT_UNITS_LUMENS     421
#define IDS_PHYS_LIGHT_DIAMETER         422
#define IDS_PHYS_LIGHT_WIDTH            423
#define IDS_AO_SIDE_FRONT               424
#define IDS_AO_SIDE_BACK                425
#define IDS_FR_MTL_AMBIENTOCCLUSION     426
#define IDC_SAMPLING_SAMPLES_MAX        1003
#define IDC_SAMPLING_SAMPLES_MAX_S      1004
#define IDC_SAMPLING_TIME_H             1005
#define IDC_DIFFUSE_COLOR               1005
#define IDC_WHITEBALANCE                1005
#define IDC_SAMPLING_TIME_H_S           1006
#define IDC_DIFFUSE_TEXMAP              1006
#define IDC_BG_IBLINTENSITY             1006
#define IDC_SAMPLING_TIME_M             1007
#define IDC_REFLECT_COLOR               1007
#define IDC_ARITHM_COLOR1               1007
#define IDC_DISTANCE_TEXMAP             1007
#define IDC_BG_IBLMAP                   1007
#define IDC_SAMPLING_TIME_M_S           1008
#define IDC_REFLECT_TEXMAP              1008
#define IDC_BLEND_MAT1                  1008
#define IDC_ARITHM_COLOR1_TEXMAP        1008
#define IDC_EMISSION_TEXMAP             1008
#define IDC_BG_BACKPLATEMAP             1008
#define IDC_BG_SKYBACKPLATEMAP          1008
#define IDC_SAMPLING_TIME_S             1009
#define IDC_REFLECT_ROUGHNESS_TEXMAP    1009
#define IDC_MATERIAL_DISPLACEMENT       1009
#define IDC_CONTRAST                    1009
#define IDC_BG_REFLECTIONMAP            1009
#define IDC_BG_SKYREFLECTIONMAP         1009
#define IDC_SAMPLING_TIME_S_S           1010
#define IDC_REFRACT_COLOR               1010
#define IDC_BG_REFRACTIONMAP            1010
#define IDC_BG_SKYREFRACTIONMAP         1010
#define IDC_RENDER_MODE                 1011
#define IDC_REFRACT_TEXMAP              1011
#define IDC_TINT                        1011
#define IDC_BG_SKYAZIMUTH               1011
#define IDC_IMAGE_FILTER                1012
#define IDC_REFRACT_ROUGHNESS_TEXMAP    1012
#define IDC_ISO                         1012
#define IDC_BG_SKYALTITUDE              1012
#define IDC_ADAPTIVE_THRESH_S           1012
#define IDC_SAMPLING_NOISE_THRESHOLD_S  1012
#define IDC_MAX_RAY_DEPTH               1013
#define IDC_NORMAL_TEXMAP               1013
#define IDC_BG_SKYHOURS                 1013
#define IDC_SAMPLING_SAMPLES_MIN        1013
#define IDC_MAX_RAY_DEPTH_S             1014
#define IDC_EMISSION_COLOR              1014
#define IDC_NORMAL_TEXMAP2              1014
#define IDC_SHUTTERSPEED                1014
#define IDC_BG_SKYMINUTES               1014
#define IDC_NORMAL_ADDITIONALBUMP_TEXMAP 1014
#define IDC_SAMPLING_SAMPLES_MIN_S      1014
#define IDC_USE_CPU                     1015
#define IDC_CLAMP_IRRADIANCE_VAL        1015
#define IDC_NORMAL_TEXMAP3              1015
#define IDC_BG_SKYSECONDS               1015
#define IDC_LOCK_MAX                    1016
#define IDC_OSL_FILE_BUTTON             1016
#define IDC_MAX_RAY_DEPTH_S2            1016
#define IDC_CLAMP_IRRADIANCE_VAL_S      1016
#define IDC_NORMAL_TEXMAP4              1016
#define IDC_BG_IBLBACKPLATEMAP          1016
#define IDC_OSL_TEXT                    1017
#define IDC_INTERACTIVE_MODE            1017
#define IDC_DIFFUSE_ROUGHNESS           1017
#define IDC_BG_SKYMONTH                 1017
#define IDC_IMAGE_FILTER_WIDTH          1018
#define IDC_DIFFUSE_ROUGHNESS_S         1018
#define IDC_SENSORWIDTH                 1018
#define IDC_BG_SKYDAY                   1018
#define IDC_GPU_COUNT                   1019
#define IDC_REFLECT_ROUGHNESS           1019
#define IDC_BLEND_WEIGHT                1019
#define IDC_BG_SKYYEAR                  1019
#define IDC_GPU_COUNT_S                 1020
#define IDC_REFLECT_ROUGHNESS_S         1020
#define IDC_BLEND_WEIGHT_S              1020
#define IDC_BURN                        1020
#define IDC_BG_SKYTIMEZONE              1020
#define IDC_REFLECT_IOR                 1021
#define IDC_AUTOTEST_GO                 1021
#define IDC_EMISSIVE_MULT               1021
#define IDC_MAX_LIGHT_BOUNCES           1021
#define IDC_OVERWRITE_DOF               1021
#define IDC_OVERWRITE_DOF_SETTINGS      1021
#define IDC_EMISSIVE_WATTS              1021
#define IDC_BG_SKYLATITUDE              1021
#define IDC_REFLECT_IOR_S               1022
#define IDC_EMISSIVE_MULT_S             1022
#define IDC_USE_MOTION_BLUR             1022
#define IDC_EMISSIVE_WATTS_S            1022
#define IDC_PRESCALE                    1022
#define IDC_BG_SKYLONGITUDE             1022
#define IDC_REFRACT_ROUGHNESS           1023
#define IDC_EMISSIVE_LUMENS             1023
#define IDC_BG_SKYHAZE                  1023
#define IDC_APERTURE_BLADES             1024
#define IDC_REFRACT_ROUGHNESS_S         1024
#define IDC_AUTOTEST_FILTER             1024
#define IDC_MAX_BOUNCES_S               1024
#define IDC_MAX_LIGHT_BOUNCES_S         1024
#define IDC_EMISSIVE_LUMENS_S           1024
#define IDC_POSTSCALE                   1024
#define IDC_BG_SKYGLOW                  1024
#define IDC_APERTURE_BLADES_S           1025
#define IDC_REFRACT_IOR                 1025
#define IDC_AUTOTEST_PASSES             1025
#define IDC_BG_SKYREDBLUESHIFT          1025
#define IDC_IMAGE_FILTER_WIDTH_S        1026
#define IDC_REFRACT_IOR_S               1026
#define IDC_FOCAL_LENGTH                1026
#define IDC_MAX_LIGHT_BOUNCES_S2        1026
#define IDC_EMISSIVE_CANDELA_S          1026
#define IDC_BG_SKYGROUNDCOLOR           1026
#define IDC_EMISSION_INTENSITY          1027
#define IDC_FOCAL_LENGTH_S              1027
#define IDC_EMISSIVE_KELVIN             1027
#define IDC_BG_SKYSUNDISC               1027
#define IDC_FOCAL_DIST                  1028
#define IDC_FOCUS_DIST                  1028
#define IDC_EMISSION_INTENSITY_S        1028
#define IDC_AUTOTEST_PASSES_S           1028
#define IDC_EMISSIVE_KELVIN_S           1028
#define IDC_BG_SKYHORIZONHEIGHT         1028
#define IDC_BG_SKYGROUNDALBEDO          1028
#define IDC_FOCAL_DIST_S                1029
#define IDC_AUTOTEST_REPEAT             1029
#define IDC_CHECK1                      1029
#define IDC_FM_CASTS_SHADOWS            1029
#define IDC_SM_CASTSHADOWS              1029
#define IDC_CLAMP_IRRADIANCE            1029
#define IDC_NORMAL_ISBUMP               1029
#define IDC_FOCUS_DIST_S                1029
#define IDC_WARNING_DONTSHOW            1029
#define IDC_UBER_GLOSSYUSE              1029
#define IDC_OVERRIDE                    1029
#define IDC_BG_USE                      1029
#define IDC_ENABLE_STAMP                1029
#define IDC_UBER_SSS_USE_DIFFUSE_COLOR  1029
#define IDC_FIRERENDER_PORTALLIGHT_ENABLED 1029
#define IDC_FIRERENDER_IES_LIGHT_SHADOWS_ENABLED 1029
#define IDC_CPU_OVERRIDE_THREADS        1029
#define IDC_UBER3_DIFFUSE_ENABLE        1029
#define IDC_FSTOP                       1030
#define IDC_REPEAT_PASSES_S             1030
#define IDC_AUTOTEST_REPEAT_S           1030
#define IDC_REFLECTIONS                 1030
#define IDC_UBER_CCUSE                  1030
#define IDC_BG_SKYHORIZONBLUR           1030
#define IDC_NORMAL_SWAPRG               1030
#define IDC_FIRERENDER_PORTALLIGHT_ENABLED2 1030
#define IDC_UBER3_DIFFUSE_USE_SHADER_NORMAL 1030
#define IDC_FSTOP_S                     1031
#define IDC_BLEND_MAT0                  1031
#define IDC_BG_SKYINTENSITY             1031
#define IDC_NORMAL_INVERTG              1031
#define IDC_SENSOR_SIZE                 1032
#define IDC_MF_COLOR_TEXMAP             1032
#define IDC_BG_IBLREFLECTIONMAP         1032
#define IDC_NORMAL_INVERTR              1032
#define IDC_UBER_GLOSSYUSE3             1032
#define IDC_UBER_REFLECTION_USE         1032
#define IDC_UBER_USE_REFLECTION         1032
#define IDC_SENSOR_SIZE_S               1033
#define IDC_MF_COLOR                    1033
#define IDC_BG_IBLREFRACTIONMAP         1033
#define IDC_UBER_GLOSSYUSE4             1033
#define IDC_UBER_REFRACTION_USE         1033
#define IDC_UBER_USE_REFRACTION         1033
#define IDC_EXPOSURE                    1034
#define IDC_MF_ROUGHNESS                1034
#define IDC_CAMERA_EXPOSURE             1034
#define IDC_OVERWRITE_DOF_SETTINGS2     1034
#define IDC_BG_SKYFILTER                1034
#define IDC_UBER_GLOSSYUSE5             1034
#define IDC_UBER_COATING_USE            1034
#define IDC_UBER_USE_COATING            1034
#define IDC_UBER_USE_COAT               1034
#define IDC_EXPOSURE_S                  1035
#define IDC_MF_ROUGHNESS_TEXMAP         1035
#define IDC_CAMERA_EXPOSURE_S           1035
#define IDC_BG_SKYSHADOWSOFTNESS        1035
#define IDC_MF_ROUGHNESS_S              1036
#define IDC_MOTION_BLUR_SCALE           1036
#define IDC_BG_SKYSATURATION            1036
#define IDC_UBER_GLOSSYUSE6             1036
#define IDC_UBER_SSS_USE                1036
#define IDC_UBER_USE_SSS                1036
#define IDC_AA_GRID_SIZE                1037
#define IDC_REF_COLOR                   1037
#define IDC_WARD_ROTATION               1037
#define IDC_CAMERA_EXPOSURE_S2          1037
#define IDC_MOTION_BLUR_SCALE_S         1037
#define IDC_UBER_GLOSSYUSE7             1037
#define IDC_UBER_SUB_SURFACE_SCATTERING_USE 1037
#define IDC_AA_GRID_SIZE_S              1038
#define IDC_REF_COLOR_TEXMAP            1038
#define IDC_WARD_ROTATION_S             1038
#define IDC_UBER_GLOSSYUSE8             1038
#define IDC_UBER_ABSORPTION_USE         1038
#define IDC_BUCKET_SIZE                 1039
#define IDC_MF_ROUGHNESS2               1039
#define IDC_UBER_GLOSSYUSE9             1039
#define IDC_UBER_EMISSIVE_USE           1039
#define IDC_UBER_USE_EMISSIVE           1039
#define IDC_BUCKET_SIZE_S               1040
#define IDC_WARD_ROUGHNESSY             1040
#define IDC_UBER_GLOSSYUSE10            1040
#define IDC_UBER_MATERIAL_SETTINGS_USE  1040
#define IDC_VFB_REFRESH                 1041
#define IDC_WARD_ROUGHNESSY_S           1041
#define IDC_UBER_GLOSSYUSE11            1041
#define IDC_VFB_REFRESH_S               1042
#define IDC_ARITHM_COLOR0               1042
#define IDC_WARD_ROUGHNESSY_TEXMAP      1042
#define IDC_MEDIT_QUALITY               1043
#define IDC_TONEMAP_MODE                1043
#define IDC_ARITHM_COLOR0_TEXMAP        1043
#define IDC_MF_ROUGHNESS_S2             1043
#define IDC_MEDIT_QUALITY_S             1044
#define IDC_TONEMAP_LINEAR_SCALE        1044
#define IDC_INPUTLU_VALUE               1044
#define IDC_MF_ROUGHNESS_TEXMAP2        1044
#define IDC_TONEMAP_SCALE_S             1045
#define IDC_TONEMAP_LINEAR_SCALE_S      1045
#define IDC_WARD_ROTATION2              1045
#define IDC_UBER_CCROTATION             1045
#define IDC_TEXMAP_SIZE                 1045
#define IDC_TONEMAP_PHOTOLINEAR_SENSITIVITY 1046
#define IDC_ARITHM_OP                   1046
#define IDC_WARD_ROTATION_S2            1046
#define IDC_UBER_CCROTATION_S           1046
#define IDC_TEXMAP_SIZE_S               1046
#define IDC_TONEMAP_PHOTOLINEAR_SENSITIVITY_S 1047
#define IDC_BV_COLOR0                   1047
#define IDC_WARD_ROUGHNESSY2            1047
#define IDC_UBER_CCROUGHNESSY           1047
#define IDC_TONEMAP_PHOTOLINEAR_EXPOSURE 1048
#define IDC_BV_COLOR1                   1048
#define IDC_WARD_ROUGHNESSY_S2          1048
#define IDC_UBER_CCROUGHNESSY_S         1048
#define IDC_TONEMAP_PHOTOLINEAR_EXPOSURE_S 1049
#define IDC_BV_COLOR0_TEXMAP            1049
#define IDC_WARD_ROUGHNESSY_TEXMAP2     1049
#define IDC_UBER_CCROUGHNESSY_T         1049
#define IDC_TONEMAP_PHOTOLINEAR_FSTOP   1050
#define IDC_BV_COLOR1_TEXMAP            1050
#define IDC_MF_ROUGHNESS3               1050
#define IDC_TONEMAP_PHOTOLINEAR_FSTOP_S 1051
#define IDC_BV_WEIGHT                   1051
#define IDC_MF_ROUGHNESS_S3             1051
#define IDC_TONEMAP_REINHARD_BURN       1052
#define IDC_BV_WEIGHT_S                 1052
#define IDC_MF_ROUGHNESS_TEXMAP3        1052
#define IDC_TONEMAP_REINHARD_BURN_S     1053
#define IDC_BV_WEIGHT_TEXMAP            1053
#define IDC_MF_ROUGHNESS4               1053
#define IDC_TONEMAP_REINHARD_PRESCALE   1054
#define IDC_REFR_COLOR                  1054
#define IDC_TONEMAP_REINHARD_PRESCALE_S 1055
#define IDC_REFR_COLOR_TEXMAP           1055
#define IDC_TONEMAP_REINHARD_POSTSCALE  1056
#define IDC_REFR_IOR                    1056
#define IDC_TONEMAP_REINHARD_POSTSCALE_S 1057
#define IDC_REFR_IOR_S                  1057
#define IDC_REFR_ROUGHNESS              1058
#define IDC_REFR_COLOR2                 1058
#define IDC_GENERATES_CAUSTICS          1059
#define IDC_REFR_ROUGHNESS_S            1059
#define IDC_DUMPTRACE_CHECK             1059
#define IDC_TRACEDUMP_CHECK             1059
#define IDC_REFR_COLOR_TEXMAP2          1059
#define IDC_REFR_ROUGHNESS_TEXMAP       1060
#define IDC_MF_ROUGHNESS_S4             1060
#define IDC_TRACEDUMP_CHECK2            1060
#define IDC_WARD_COLOR                  1061
#define IDC_SM_EMISSION_STRENGHT        1061
#define IDC_TEXTURE_COMPRESSION_CHECK   1062
#define IDC_WARD_COLOR_TEXMAP           1062
#define IDC_SM_EMISSION_STRENGHT_S      1062
#define IDC_WARD_ROUGHNESSX             1063
#define IDC_WARD_ROUGHNESSX_S           1064
#define IDC_WARD_ROUGHNESSX_TEXMAP      1065
#define IDC_EMISSIVE_COLOR              1066
#define IDC_WARD_ROTATION_TEXMAP        1066
#define IDC_EMISSIVE_COLOR_TEXMAP       1067
#define IDC_WARD_ROUGHNESSX2            1067
#define IDC_UBER_CCROUGHNESSX           1067
#define IDC_DIFFUSE_ROUGHNESS_TEXMAP    1068
#define IDC_EMISSIVE_KELVIN_SWATCH      1068
#define IDC_WARD_COLOR2                 1068
#define IDC_BLEND_WEIGHT_TEXMAP         1069
#define IDC_WARD_COLOR_TEXMAP2          1069
#define IDC_FRESNEL_INVEC               1070
#define IDC_WARD_ROUGHNESSX_S2          1070
#define IDC_UBER_CCROUGHNESSX_S         1070
#define IDC_FRESNEL_IOR                 1071
#define IDC_WARD_ROUGHNESSX_TEXMAP2     1071
#define IDC_UBER_CCROUGHNESSX_T         1071
#define IDC_FRESNEL_IOR_S               1072
#define IDC_WARD_ROTATION_TEXMAP2       1072
#define IDC_UBER_CCROTATION_T           1072
#define IDC_FRESNEL_N                   1073
#define IDC_DISPLACEMENT_MAXHEIGHT      1073
#define IDC_MF_ROUGHNESS_TEXMAP4        1073
#define IDC_FRESNEL_INVEC_TEXMAP        1074
#define IDC_FRESNEL_IOR_S2              1074
#define IDC_DISPLACEMENT_MAXHEIGHT_S    1074
#define IDC_FRESNEL_N_TEXMAP            1075
#define IDC_DISPLACEMENT_MINHEIGHT      1075
#define IDC_REFR_IOR_S3                 1075
#define IDC_FRESNEL_INVEC_TEXMAP2       1076
#define IDC_FRESNEL_IOR_TEXMAP          1076
#define IDC_MF_IOR                      1076
#define IDC_DISPLACEMENT_MINHEIGHT_S    1076
#define IDC_MF_IOR_S                    1077
#define IDC_DISPLACEMENT_TEXMAP         1077
#define IDC_SM_DIFFUSE_COLOR            1078
#define IDC_SM_DIFFUSE_TEXMAP           1079
#define IDC_SM_DIFFUSE_ROUGHNESS        1080
#define IDC_SM_DIFFUSE_ROUGHNESS_S      1081
#define IDC_SM_DIFFUSE_ROUGHNESS_TEXMAP 1082
#define IDC_SM_REFL_COLOR               1083
#define IDC_SM_REFL_IOR                 1084
#define IDC_SM_REFL_IOR_S               1085
#define IDC_SM_REFL_ROUGHNESS           1086
#define IDC_SM_REFL_ROUGHNESS_S         1087
#define IDC_SM_REFL_ROUGHNESS_TEXMAP    1088
#define IDC_SM_REFL_COLOR_TEXMAP        1089
#define IDC_SM_REFR_COLOR               1090
#define IDC_SM_REFR_COLOR_TEXMAP        1091
#define IDC_SM_REFR_IOR                 1092
#define IDC_SM_REFR_IOR_S               1093
#define IDC_SM_DIFFUSE_WEIGHT           1096
#define IDC_SM_EMISSION_COLOR           1097
#define IDC_COL_COLOR                   1098
#define IDC_SM_DIFFUSE_WEIGHT_S         1098
#define IDC_COL_COLOR_TEXMAP            1099
#define IDC_SM_DIFFUSE_WEIGHT_TEXMAP    1099
#define IDC_SM_REFL_WEIGHT              1100
#define IDC_SM_REFL_WEIGHT_S            1101
#define IDC_SM_REFL_WEIGHT_TEXMAP       1102
#define IDC_SM_EMISSION_WEIGHT          1103
#define IDC_SM_EMISSION_WEIGHT_S        1104
#define IDC_SM_EMISSION_WEIGHT_TEXMAP   1105
#define IDC_DIFFUSE_NORMAL_TEXMAP       1106
#define IDC_REFLECT_NORMAL_TEXMAP       1107
#define IDC_GLOBAL_ILLUMINATION_SOLVER  1107
#define IDC_SM_REFR_WEIGHT              1108
#define IDC_TONEMAP_REINHARD            1108
#define IDC_SM_REFR_WEIGHT_S            1109
#define IDC_TONEMAP_PHOTO               1109
#define IDC_SM_REFR_WEIGHT_TEXMAP       1110
#define IDC_AA_QUALITY_PRESETS          1110
#define IDC_REFLECT_NORMAL_TEXMAP2      1111
#define IDC_REFRACT_NORMAL_TEXMAP       1111
#define IDC_UNLIMITED_BOUNCE            1111
#define IDC_LIMIT_BOUNCES               1112
#define IDC_BUTTON1                     1114
#define IDC_BROWSE_EXPORT_FILE          1114
#define IDC_WARNING_CLOSE               1114
#define IDC_BG_SKYGETLOCATION           1114
#define IDC_SEARCH                      1114
#define IDC_EXPORTMATLIB                1114
#define IDC_STAMP_RESET                 1114
#define IDC_RUN_SCRIPT_BTN              1114
#define IDC_EXPORTMATLIB2               1115
#define IDC_OPEN_TRACE_DIR              1115
#define IDC_TONEMAPPING_NONE            1116
#define IDC_TONEMAP_NONE                1116
#define IDC_FRESNEL_REFLECTANCE         1117
#define IDC_FRESNEL_REFLECTANCE_TEXMAP  1118
#define IDC_DISPLACEMENT_SUBDIVISION    1119
#define IDC_DISPLACEMENT_SUBDIVISION_S  1120
#define IDC_COMBO1                      1121
#define IDC_CAMERA_TYPES                1121
#define IDC_DISPLACEMENT_CREASEWEIGHT   1121
#define IDC_UBER_REFLECTION_MODE        1121
#define IDC_FIRERENDER_IES_LIGHT_PROFILE 1121
#define IDC_EXPORT_COMRESSION           1121
#define IDC_NORMAL_STRENGTH             1122
#define IDC_RENDER_DEVICE               1122
#define IDC_DISPLACEMENT_CREASEWEIGHT_S 1122
#define IDC_COMBO3                      1122
#define IDC_UBER_COAT_MODE              1122
#define IDC_NORMAL_STRENGTH_S           1123
#define IDC_VERSION                     1124
#define IDC_BUMP_STRENGTH               1124
#define IDC_MATERIAL_SURFACE            1125
#define IDC_NORMAL_STRENGTH_S2          1125
#define IDC_BUMP_STRENGTH_S             1125
#define IDC_MATERIAL_VOLUME             1126
#define IDC_MATERIAL_CAUSTICS           1127
#define IDC_DOF_STATIC_FD               1128
#define IDC_MATERIAL_CAUSTICS2          1128
#define IDC_MATERIAL_SHADOWCATCHER      1128
#define IDC_DOF_STATIC_S                1129
#define IDC_DOF_STATIC_SW               1129
#define IDC_DOF_STATIC_FS               1130
#define IDC_DOF_STATIC_AB               1131
#define IDC_DOF_STATIC_FL               1132
#define IDC_DOF_STATIC_SF               1133
#define IDC_ABOUT_LINKS1                1134
#define IDC_FOV                         1135
#define IDC_FOV_S                       1136
#define IDC_ABOUT2                      1136
#define IDC_USE_FOV                     1137
#define IDC_ABOUT3                      1137
#define IDC_USE_DOF                     1138
#define IDC_WARNING_MESSAGE             1139
#define IDC_STEREO_CAMERA               1139
#define IDC_MAP                         1140
#define IDC_SHAPE                       1141
#define IDC_MAP2                        1141
#define IDC_BACKGROUNG_MAP              1141
#define IDC_INTENSITY                   1142
#define IDC_INTENSITY_S                 1143
#define IDC_RADIUS                      1144
#define IDC_RADIUS_S                    1145
#define IDC_SHADOWS                     1148
#define IDC_REFLECTIONS_ROUGHNESS       1149
#define IDC_REFLECTIONS_ROUGHNESS_S     1150
#define IDC_COLOR                       1151
#define IDC_AZIMUTH                     1151
#define IDC_SHADOWS2                    1152
#define IDC_ACTIVE                      1152
#define IDC_REFLECTIONS_STRENGTH        1153
#define IDC_REFLECTIONS_ROUGHNESS_S2    1154
#define IDC_REFLECTIONS_STRENGTH_S      1154
#define IDC_REFLECTIONS_COLOR           1155
#define IDC_AZIMUTH_S                   1156
#define IDC_ALTITUDE                    1157
#define IDC_ALTITUDE_S                  1158
#define IDC_ALBEDO                      1159
#define IDC_ALBEDO_S                    1160
#define IDC_TURBIDITY                   1161
#define TURBIDITY                       1162
#define IDC_TURBIDITY_S                 1162
#define IDC_RD_WATTS                    1163
#define IDC_BACKGROUND                  1163
#define IDC_RD_LUMENS                   1164
#define IDC_PORTAL                      1164
#define IDC_RD_RGB                      1166
#define IDC_RD_KELVIN                   1167
#define IDC_TYPE_IBL                    1168
#define IDC_TYPE_ANALYTICAL             1169
#define IDC_UBER_REFRCOLOR              1187
#define IDC_UBER_REFRCOLOR_T            1188
#define IDC_UBER_DIFFNORMAL             1189
#define IDC_UBER_CCNORMAL               1190
#define IDC_UBER_REFRNORMAL             1191
#define IDC_UBER_CCROUGHNESS            1192
#define IDC_UBER_CCCOLOR                1193
#define IDC_UBER_CCCOLOR_T              1194
#define IDC_UBER_CCROUGHNESS_S          1195
#define IDC_UBER_CCROUGHNESS_T          1196
#define IDC_UBER_DIFFLEVEL              1197
#define IDC_UBER_DIFFLEVEL_S            1198
#define IDC_UBER_DIFFLEVEL_T            1199
#define IDC_UBER_GLOSSYLEVEL            1200
#define IDC_UBER_GLOSSYLEVEL_S          1201
#define IDC_UBER_GLOSSYLEVEL_T          1202
#define IDC_UBER_CCLEVEL                1203
#define IDC_UBER_CCLEVEL_S              1204
#define IDC_UBER_CCLEVEL_T              1205
#define IDC_UBER_REFRLEVEL              1206
#define IDC_UBER_REFRLEVEL_S            1207
#define IDC_UBER_REFRLEVEL_T            1208
#define IDC_UBER_TRANSPLEVEL            1209
#define IDC_UBER_TRANSPLEVEL_S          1210
#define IDC_UBER_TRANSPLEVEL_T          1211
#define IDC_UBER_CCIOR                  1212
#define IDC_UBER_CCIOR_S                1213
#define IDC_UBER_REFRIOR                1214
#define IDC_UBER_CCIOR_S2               1215
#define IDC_UBER_REFRIOR_S              1216
#define IDC_UBER_DIFFCOLOR              1217
#define IDC_UBER_DIFFCOLOR_T            1218
#define IDC_UBER_GLOSSYCOLOR            1219
#define IDC_UBER_GLOSSYCOLOR_T          1220
#define IDC_UBER_GLOSSYROUGHNESS        1221
#define IDC_UBER_DIFFWEIGHT             1221
#define IDC_UBER_DIFFUSE_WEIGHT         1221
#define IDC_UBER_GLOSSYROUGHNESS_S      1222
#define IDC_UBER_DIFFWEIGHT_T           1222
#define IDC_UBER_DIFFUSE_WEIGHT_T       1222
#define IDC_UBER_GLOSSYROUGHNESS_T      1223
#define IDC_UBER_DIFFWEIGHT6            1223
#define IDC_UBER_DIFFUSE_ROUGHNESS      1223
#define IDC_UBER_GLOSSYIOR              1224
#define IDC_UBER_GLOSSYIOR_S            1225
#define IDC_UBER_GLOSSYNORMAL           1226
#define IDC_UBER_REFRROUGHNESS          1227
#define IDC_UBER_REFRROUGHNESS_S        1228
#define IDC_UBER_REFRROUGHNESS_T        1229
#define IDC_UBER_TRANSPCOLOR            1230
#define IDC_UBER_TRANSPCOLOR_T          1231
#define IDC_UBER_DISPLACEMENT           1232
#define IDC_UBERCAUSTICS                1233
#define IDC_UBERSHADOWCATCHER           1234
#define IDC_UBER_GLOSSYROTATION         1235
#define IDC_UBER_GLOSSYROTATION_S       1236
#define IDC_UBER_GLOSSYROTATION_T       1237
#define IDC_UBER_GLOSSYROUGHNESSX       1238
#define IDC_UBER_GLOSSYROUGHNESSX_S     1239
#define IDC_UBER_GLOSSYROUGHNESSX_T     1240
#define IDC_UBER_GLOSSYROUGHNESSY       1241
#define IDC_UBER_GLOSSYROUGHNESSY_S     1242
#define IDC_UBER_GLOSSYROUGHNESSY_T     1243
#define IDC_UBER_REFRROUGHNESSX         1244
#define IDC_WARNINGS_SUPPRESS           1244
#define IDC_UBER_DIFFCOLOR_MUL          1244
#define IDC_UBER_DIFFFUSE_COLOR_MUL     1244
#define IDC_UBER_DIFFUSE_COLOR_MUL      1244
#define IDC_WARNINGS_SUPPRESS2          1245
#define IDC_WARNINGS_SUPPRESS_GLOBAL    1245
#define IDC_SIGMAA                      1245
#define IDC_ABSORPTION_COLOR            1245
#define IDC_ABSORPTION_MULTIPLIER       1246
#define IDC_UBER_DIFFCOLOR_MUL_S        1246
#define IDC_UBER_DIFFUSE_COLOR_MUL_S    1246
#define IDC_ABSORPTION_MULTIPLIER_S     1247
#define IDC_UBER_DIFFWEIGHT_MUL         1247
#define IDC_UBER_DIFFUSE_WEIGHT_MUL     1247
#define IDC_SCATTERING_COLOR            1248
#define IDC_UBER_DIFFWEIGHT_MUL_S       1248
#define IDC_UBER_DIFFUSE_WEIGHT_MUL_S   1248
#define IDC_SCATTERING_MULTIPLIER       1249
#define IDC_UBER_DIFFWEIGHT_T6          1249
#define IDC_UBER_DIFFUSE_ROUGHNESS_T    1249
#define IDC_SCATTERING_MULTIPLIER_S     1250
#define IDC_UBER_DIFFWEIGHT_MUL6        1250
#define IDC_UBER_DIFFUSE_ROUGHNESS_MUL  1250
#define IDC_UBER_DIFFWEIGHT_MUL_S6      1251
#define IDC_UBER_DIFFUSE_ROUGHNESS_MUL_S 1251
#define IDC_EMISSION_MULTIPLIER         1252
#define IDC_EMISSION_MULTIPLIER_S       1253
#define IDC_SCATTERING_PHASE            1254
#define IDC_SCATTERING_PHASE_S          1255
#define IDC_MULTISCATTER                1256
#define IDC_UBER_DIFFCOLOR2             1257
#define IDC_UBER_REFLECTION_COLOR       1257
#define IDC_UBER_DIFFCOLOR_T2           1258
#define IDC_UBER_REFLECTION_COLOR_T     1258
#define IDC_UBER_DIFFWEIGHT_MUL7        1259
#define IDC_UBER_REFLECTION_COLOR_MUL   1259
#define IDC_UBER_DIFFCOLOR_MUL_S2       1260
#define IDC_UBER_REFLECTION_COLOR_MUL_S 1260
#define IDC_LIST1                       1261
#define IDC_UBER_DIFFWEIGHT2            1261
#define IDC_UBER_REFLECTION_WEIGHT      1261
#define IDC_LIST_HW                     1261
#define IDB_LOGO                        1262
#define IDR_SIMPLIFIED                  1262
#define IDC_UBER_DIFFWEIGHT_T2          1262
#define IDC_UBER_REFLECTION_WEIGHT_T    1262
#define IDC_ABOUT_LINKS2                1263
#define IDR_LINEAR                      1263
#define IDC_UBER_DIFFCOLOR_MUL_S5       1263
#define IDC_UBER_REFLECTION_WEIGHT_MUL_S 1263
#define IDR_NONLINEAR                   1264
#define IDC_UBER_DIFFWEIGHT_MUL8        1264
#define IDC_UBER_REFLECTION_WEIGHT_MUL  1264
#define IDC_WHITEBALANCE_S              1265
#define IDC_UBER_DIFFWEIGHT3            1265
#define IDC_UBER_REFLECTION_ROUGHNESS   1265
#define IDC_CONTRAST_S                  1266
#define IDC_BG_SKYAZIMUTH_S             1266
#define IDC_UBER_DIFFWEIGHT_T3          1266
#define IDC_UBER_REFLECTION_ROUGHNESS_T 1266
#define IDC_ISO_S                       1267
#define IDC_BG_SKYALTITUDE_S            1267
#define IDC_UBER_DIFFCOLOR_MUL_S6       1267
#define IDC_UBER_REFLECTION_ROUGHNESS_MUL_S 1267
#define IDC_SHUTTERSPEED_S              1268
#define IDC_BG_SKYHOURS_S               1268
#define IDC_UBER_DIFFWEIGHT_MUL9        1268
#define IDC_UBER_REFLECTION_ROUGHNESS_MUL 1268
#define IDC_SENSORWIDTH_S               1269
#define IDC_UBER_DIFFWEIGHT4            1269
#define IDC_UBER_REFLECTION_ANISO       1269
#define IDC_BURN_S                      1270
#define IDC_BG_SKYSECONDS_S             1270
#define IDC_UBER_DIFFWEIGHT_T4          1270
#define IDC_UBER_REFLECTION_ANSIO_T     1270
#define IDC_UBER_REFLECTION_ANISO_T     1270
#define IDC_UBER_REFLECTION_ROUGHNESS2  1270
#define IDC_FIRERENDER_IES_LIGHT_TEMPERATURE_C 1270
#define IDC_PRESCALE_S                  1271
#define IDC_UBER_DIFFCOLOR_MUL_S7       1271
#define IDC_UBER_REFLECTION_ANISO_MUL_S 1271
#define IDC_POSTSCALE_S                 1272
#define IDC_BG_SKYMONTH_S               1272
#define IDC_UBER_DIFFWEIGHT_MUL10       1272
#define IDC_UBER_REFLECTION_ANISOTROPY_MUL 1272
#define IDC_UBER_REFLECTION_ANISO_MUL   1272
#define IDR_SIMPLIFIED2                 1273
#define IDR_NONE                        1273
#define IDC_BG_SKYDAY_S                 1273
#define IDC_UBER_DIFFWEIGHT5            1273
#define IDC_UBER_REFLECTION_ANISO_ROT   1273
#define IDC_BG_SKYYEAR_S                1274
#define IDC_UBER_DIFFWEIGHT_T5          1274
#define IDC_UBER_REFLECTION_ANISO_ROT_T 1274
#define IDC_BG_SKYTIMEZONE_S            1275
#define IDC_UBER_DIFFCOLOR_MUL_S8       1275
#define IDC_UBER_REFLECTION_ANISOTROPY_ROT_MUL_S 1275
#define IDC_UBER_REFLECTION_ANISO_ROT_MUL_S 1275
#define IDC_CHECK2                      1276
#define IDC_USEVOLUME                   1276
#define IDC_BG_IBLUSE                   1276
#define IDC_OVERRIDE_MAX_PREVIEW_SHAPES 1276
#define IDC_UBER_SSS_SINGLESCATTERING   1276
#define IDC_UBER3_DIFFUSE_SEPARATE_BACKSCATTERING_COLOR 1276
#define IDC_EXPORT_USEEXPTERNAL_FILES   1276
#define IDC_ABSORPTION_TEXMAP           1277
#define IDC_BG_BACKPLATEUSE             1277
#define IDC_BG_SKYBACKPLATEUSE          1277
#define IDC_DISTANCE                    1278
#define IDC_BG_REFLECTIONUSE            1278
#define IDC_BG_SKYREFLECTIONUSE         1278
#define IDC_DISTANCE_S                  1279
#define IDC_BG_REFRACTIONUSE            1279
#define IDC_BG_SKYREFRACTIONUSE         1279
#define IDC_BG_USEIBL                   1280
#define IDC_UBER_DIFFWEIGHT_MUL11       1280
#define IDC_UBER_REFLECTION_ANISOTROPY_ROT_MUL 1280
#define IDC_UBER_REFLECTION_ANISO_ROT_MUL 1280
#define IDC_BG_USESKY                   1281
#define IDC_UBER_DIFFCOLOR3             1281
#define IDC_UBER_REFLECTION_IOR         1281
#define IDC_BG_SKYANALYTICAL            1282
#define IDC_UBER_DIFFCOLOR_T3           1282
#define IDC_UBER_REFLECTION_IOR_MUL_T   1282
#define IDC_UBER_REFLECTION_IOR_T       1282
#define IDC_BG_SKYDATETIMELOC           1283
#define IDC_UBER_DIFFWEIGHT_MUL12       1283
#define IDC_UBER_REFLECTION_IOR_MUL     1283
#define IDC_BG_SKYDAYLIGHTSAVING        1284
#define IDC_UBER_DIFFCOLOR_MUL_S3       1284
#define IDC_UBER_REFLECTION_IOR_MUL_S   1284
#define IDC_BG_IBLBACKPLATEUSE          1285
#define IDC_UBER_DIFFCOLOR4             1285
#define IDC_UBER_REFLECTION_METALNESS   1285
#define IDC_BG_SKYLONGITUDE_S           1286
#define IDC_UBER_DIFFCOLOR_T4           1286
#define IDC_UBER_REFLECTION_METALNESS_MUL_T 1286
#define IDC_UBER_REFLECTION_METALNESS_T 1286
#define IDC_BG_IBLREFLECTIONUSE         1287
#define IDC_UBER_DIFFWEIGHT_MUL13       1287
#define IDC_UBER_REFLECTION_METALNESS_MUL 1287
#define IDC_WHITEBALANCE_S15            1288
#define IDC_UBER_DIFFCOLOR_MUL_S4       1288
#define IDC_UBER_REFLECTION_METALNESS_MUL_S 1288
#define IDC_BG_SKYREDBLUESHIFT_S        1289
#define IDC_UBER_DIFFCOLOR5             1289
#define IDC_UBER_REFRACTION_COLOR       1289
#define IDC_BG_SKYSUNDISC_S             1290
#define IDC_UBER_DIFFCOLOR_T5           1290
#define IDC_UBER_REFRACTION_COLOR_T     1290
#define IDC_BG_SKYHORIZONBLUR_S         1291
#define IDC_UBER_DIFFCOLOR_MUL_S9       1291
#define IDC_UBER_REFRACTION_COLOR_MUL_S 1291
#define IDC_BG_SKYHORIZONHEIGHT_S       1292
#define IDC_UBER_DIFFWEIGHT7            1292
#define IDC_UBER_REFRACTION_WEIGHT      1292
#define IDC_BG_IBLCOLOR                 1293
#define IDC_UBER_DIFFWEIGHT_T7          1293
#define IDC_UBER_REFRACTION_WEIGHT_T    1293
#define IDC_BG_IBLINTENSITY_S           1294
#define IDC_UBER_DIFFWEIGHT8            1294
#define IDC_UBER_REFRACTION_ROUGHNESS   1294
#define IDC_BG_SKYMINUTES_S             1295
#define IDC_UBER_DIFFWEIGHT_T8          1295
#define IDC_UBER_REFRACTION_ROUGHNESS_T 1295
#define IDC_BG_SKYLATITUDE_S            1296
#define IDC_UBER_DIFFWEIGHT9            1296
#define IDC_UBER_REFRACTION_IOR         1296
#define IDC_BG_SKYHAZE_S                1297
#define IDC_UBER_DIFFWEIGHT_T9          1297
#define IDC_UBER_REFRACTION_IOR_T       1297
#define IDC_BG_SKYGLOW_S                1298
#define IDC_UBER_DIFFCOLOR6             1298
#define IDC_UBER_COAT_COLOR             1298
#define IDC_BG_SKYGLOW_S2               1299
#define IDC_BG_SKYINTENSITY_S           1299
#define IDC_UBER_DIFFCOLOR_T6           1299
#define IDC_UBER_COAT_COLOR_T           1299
#define IDC_BG_IBLREFRACTIONUSE         1300
#define IDC_UBER_DIFFWEIGHT_MUL14       1300
#define IDC_UBER_REFRACTION_COLOR_MUL   1300
#define IDC_SEARCHBOX                   1301
#define IDC_BG_SKYSATURATION_S          1301
#define IDC_UBER_DIFFWEIGHT_MUL15       1301
#define IDC_UBER_REFRACTION_WEIGHT_MUL  1301
#define IDC_RESULTSBOX                  1302
#define IDC_BG_SKYSHADOWSOFTNESS_S      1302
#define IDC_UBER_DIFFWEIGHT_MUL16       1302
#define IDC_UBER_REFRACTION_ROUGHNESS_MUL 1302
#define IDC_UBER_DIFFWEIGHT_MUL17       1303
#define IDC_UBER_REFRACTION_IOR_MUL     1303
#define IDC_UBER_DIFFCOLOR_MUL_S10      1304
#define IDC_UBER_COAT_COLOR_MUL_S       1304
#define IDC_UBER_DIFFWEIGHT10           1305
#define IDC_UBER_COAT_WEIGHT            1305
#define IDC_UBER_DIFFWEIGHT_T10         1306
#define IDC_UBER_COAT_WEIGHT_T          1306
#define IDC_BG_SKYNOW                   1307
#define IDC_UBER_DIFFWEIGHT11           1307
#define IDC_UBER_COAT_ROUGHNESS         1307
#define IDC_UBER_DIFFWEIGHT_T11         1308
#define IDC_UBER_COAT_ROUGHNESS_T       1308
#define IDC_UBER_DIFFCOLOR_MUL_S12      1309
#define IDC_UBER_REFRACTION_WEIGHT_MUL_S 1309
#define IDC_MEMATS                      1310
#define IDC_SCENEMATS                   1311
#define IDC_UBER_DIFFCOLOR_MUL_S13      1311
#define IDC_UBER_REFRACTION_ROUGHNESS_MUL_S 1311
#define IDC_MLMATS                      1312
#define IDC_UBER_DIFFWEIGHT_T12         1312
#define IDC_UBER_COAT_NORMAL_T          1312
#define IDC_BG_ENABLEALPHA              1313
#define IDC_UBER_DIFFCOLOR_MUL_S14      1313
#define IDC_UBER_REFRACTION_IOR_MUL_S   1313
#define IDC_UBER_DIFFCOLOR_MUL_S15      1314
#define IDC_UBER_COAT_WEIGHT_MUL_S      1314
#define IDC_IBL_LINKS                   1315
#define IDC_UBER_DIFFCOLOR_MUL_S16      1315
#define IDC_UBER_COAT_ROUGHNESS_MUL_S   1315
#define IDC_STAMP_TEXT                  1316
#define IDC_UBER_DIFFCOLOR_MUL_S17      1316
#define IDC_UBER_COAT_NORMAL_MUL_S      1316
#define IDC_STAMP_HELP                  1317
#define IDC_UBER_DIFFWEIGHT_MUL18       1317
#define IDC_UBER_COAT_COLOR_MUL         1317
#define IDC_BG_RESET                    1318
#define IDC_UBER_DIFFWEIGHT_MUL19       1318
#define IDC_UBER_COAT_WEIGHT_MUL        1318
#define IDC_BG_USEIBL_GROUP             1319
#define IDC_UBER_DIFFWEIGHT_MUL20       1319
#define IDC_UBER_COAT_ROUGHNESS_MUL     1319
#define IDC_BG_USESKY_GROUP             1320
#define IDC_UBER_DIFFWEIGHT_MUL21       1320
#define IDC_UBER_COAT_NORMAL_MUL        1320
#define IDC_BG_SKYANALYTICAL_GROUP      1321
#define IDC_UBER_DIFFCOLOR7             1321
#define IDC_UBER_COAT_IOR               1321
#define IDC_BG_SKYDATETIMELOC_GROUP     1322
#define IDC_UBER_DIFFCOLOR_T7           1322
#define IDC_UBER_COAT_IOR_T             1322
#define IDC_RICHEDIT21                  1323
#define IDC_UBER_DIFFCOLOR_MUL_S11      1323
#define IDC_UBER_COAT_IOR_MUL_S         1323
#define IDC_UBER_INVERTMAP              1324
#define IDC_UBER_DIFFCOLOR9             1324
#define IDC_RENDER_SCRIPTS              1325
#define IDC_UBER_DIFFCOLOR8             1325
#define IDC_UBER_COAT_METALNESS         1325
#define IDC_GLOBAL_QUALITY_PRESETS      1326
#define IDC_UBER_DIFFCOLOR_T8           1326
#define IDC_UBER_COAT_METALNESS_T       1326
#define IDC_COMBO2                      1327
#define IDC_DISPLACEMENT_BOUNDARY       1327
#define IDC_UBER_DIFFCOLOR_MUL_S18      1327
#define IDC_UBER_COAT_METALNESS_MUL_S   1327
#define IDC_UBER_DIFFCOLOR_USEMAP       1328
#define IDC_UBER_DIFFUSE_COLOR_USEMAP   1328
#define IDC_UBER_DIFFWEIGHT_USEMAP2     1329
#define IDC_UBER_DIFFWEIGHT_USEMAP      1329
#define IDC_UBER_DIFFUSE_WEIGHT_USEMAP  1329
#define IDC_UBER_DIFFCOLOR_USEMAP2      1330
#define IDC_UBER_REFLECTION_COLOR_USEMAP 1330
#define IDC_UBER_DIFFWEIGHT_USEMAP3     1331
#define IDC_UBER_REFLECTION_WEIGHT_USEMAP 1331
#define IDC_UBER_DIFFWEIGHT_USEMAP4     1332
#define IDC_UBER_REFLECTION_ROUGHNESS_USEMAP 1332
#define IDC_UBER_DIFFWEIGHT_USEMAP5     1333
#define IDC_UBER_REFLECTION_ANISO_USEMAP 1333
#define IDC_UBER_DIFFWEIGHT_USEMAP6     1334
#define IDC_UBER_REFLECTION_ANISO_ROT_USEMAP 1334
#define IDC_UBER_DIFFWEIGHT_USEMAP7     1335
#define IDC_UBER_DIFFUSE_ROUGHNESS_USEMAP 1335
#define IDC_UBER_DIFFCOLOR_USEMAP3      1336
#define IDC_UBER_REFLECTION_IOR_USEMAP  1336
#define IDC_UBER_DIFFCOLOR_USEMAP4      1337
#define IDC_UBER_REFLECTION_METALNESS_USEMAP 1337
#define IDC_UBER_DIFFCOLOR_USEMAP5      1338
#define IDC_UBER_REFRACTION_COLOR_USEMAP 1338
#define IDC_UBER_DIFFWEIGHT_USEMAP8     1339
#define IDC_UBER_REFRACTION_WEIGHT_USEMAP 1339
#define IDC_UBER_DIFFWEIGHT_USEMAP9     1340
#define IDC_UBER_REFRACTION_ROUGHNESS_USEMAP 1340
#define IDC_UBER_DIFFWEIGHT_USEMAP10    1341
#define IDC_UBER_REFRACTION_IOR_USEMAP  1341
#define IDC_CHECK3                      1342
#define IDC_UBER_REFRACTION_THIN_SURFACE 1342
#define IDC_CHECK4                      1343
#define IDC_UBER_REFRACTION_LINK_TO_REFLECTION 1343
#define IDC_UBER_DIFFCOLOR_USEMAP6      1344
#define IDC_UBER_COAT_COLOR_USEMAP      1344
#define IDC_UBER_DIFFWEIGHT_USEMAP11    1345
#define IDC_UBER_COAT_WEIGHT_USEMAP     1345
#define IDC_UBER_DIFFWEIGHT_USEMAP12    1346
#define IDC_UBER_COAT_ROUGHNESS_USEMAP  1346
#define IDC_UBER_DIFFWEIGHT_USEMAP13    1347
#define IDC_UBER_COAT_NORMAL_USEMAP     1347
#define IDC_UBER_DIFFCOLOR_USEMAP7      1348
#define IDC_UBER_COAT_IOR_USEMAP        1348
#define IDC_UBER_DIFFCOLOR_USEMAP8      1349
#define IDC_UBER_COAT_METALNESS_USEMAP  1349
#define IDC_UBER_DIFFWEIGHT_MUL22       1350
#define IDC_UBER_COAT_IOR_MUL           1350
#define IDC_UBER_DIFFWEIGHT_MUL23       1351
#define IDC_UBER_COAT_METALNESS_MUL     1351
#define IDC_UBER_DIFFCOLOR_T9           1352
#define IDC_UBER_DIFFCOLOR_MUL_S19      1353
#define IDC_UBER_DIFFWEIGHT13           1354
#define IDC_UBER_SSS_WEIGHT             1354
#define IDC_UBER_DIFFWEIGHT_T13         1355
#define IDC_UBER_SSS_WEIGHT_T           1355
#define IDC_UBER_DIFFCOLOR_USEMAP9      1356
#define IDC_UBER_DIFFWEIGHT_USEMAP14    1357
#define IDC_UBER_SSS_WEIGHT_USEMAP      1357
#define IDC_UBER_DIFFCOLOR_MUL_S20      1358
#define IDC_UBER_SSS_WEIGHT_MUL_S       1358
#define IDC_UBER_DIFFWEIGHT_MUL24       1359
#define IDC_UBER_SSS_WEIGHT_MUL_S2      1359
#define IDC_FIRERENDER_IES_LIGHT_TARGETED_S 1359
#define IDC_FIRERENDER_IES_LIGHT_TARGET_DISTANCE_S 1359
#define IDC_UBER_DIFFWEIGHT_MUL25       1360
#define IDC_UBER_SSS_WEIGHT_MUL         1360
#define IDC_UBER_SSS_WEIGHT_MUL_S3      1360
#define IDC_FIRERENDER_IES_LIGHT_VOLUME_SCALE_S 1360
#define IDC_UBER_DIFFCOLOR10            1361
#define IDC_UBER_SSS_SUBSURFACE_COLOR   1361
#define IDC_UBER_SSS_WEIGHT_MUL2        1361
#define IDC_UBER_SSS_WEIGHT_MUL_S4      1361
#define IDC_FIRERENDER_IES_LIGHT_SHADOWS_TRANSPARENCY_S 1361
#define IDC_FIRERENDER_IES_LIGHT_TARGET_DISTANCE 1361
#define IDC_UBER_DIFFCOLOR_T10          1362
#define IDC_UBER_SSS_SUBSURFACE_COLOR_T 1362
#define IDC_UBER_SSS_WEIGHT_MUL3        1362
#define IDC_FIRERENDER_IES_LIGHT_VOLUME_SCALE 1362
#define IDC_UBER_DIFFCOLOR_MUL_S21      1363
#define IDC_UBER_SSS_SUBSURFACE_COLOR_MUL_S 1363
#define IDC_UBER_SSS_WEIGHT_MUL4        1363
#define IDC_FIRERENDER_IES_LIGHT_SHADOWS_TRANSPARENCY 1363
#define IDC_FIRERENDER_PHYS_LIGHT_FALLOFF_END 1363
#define IDC_UBER_DIFFWEIGHT14           1364
#define IDC_UBER_SSS_SCATTERCOLOR       1364
#define IDC_UBER_DIFFWEIGHT_T14         1365
#define IDC_UBER_SSS_SCATTERCOLOR_T     1365
#define IDC_UBER_DIFFCOLOR_USEMAP10     1366
#define IDC_UBER_SSS_SUBSURFACE_COLOR_USEMAP 1366
#define IDC_UBER_DIFFWEIGHT_USEMAP15    1367
#define IDC_UBER_SSS_SCATTERCOLOR_USEMAP 1367
#define IDC_UBER_DIFFCOLOR_MUL_S22      1368
#define IDC_UBER_SSS_SCATTERCOLOR_MUL_S 1368
#define IDC_UBER_DIFFWEIGHT_MUL26       1369
#define IDC_UBER_SSS_SUBSURFACE_COLOR_MUL 1369
#define IDC_UBER_DIFFWEIGHT_MUL27       1370
#define IDC_UBER_SSS_SCATTERCOLOR_MUL   1370
#define IDC_UBER_DIFFCOLOR11            1371
#define IDC_UBER_SSS_ABSORPTION         1371
#define IDC_UBER_DIFFCOLOR_T11          1372
#define IDC_UBER_SSS_SCATTERAMOUNT_T    1372
#define IDC_UBER_DIFFCOLOR_MUL_S23      1373
#define IDC_UBER_SSS_SCATTERAMOUNT_MUL_S 1373
#define IDC_UBER_DIFFCOLOR_T12          1374
#define IDC_UBER_SSS_ABSORPTION_T       1374
#define IDC_UBER_DIFFCOLOR_MUL_S25      1375
#define IDC_UBER_SSS_ABSORPTION_MUL_S   1375
#define IDC_UBER_DIFFCOLOR_USEMAP11     1376
#define IDC_UBER_SSS_SCATTERAMOUNT_USEMAP 1376
#define IDC_UBER_DIFFCOLOR12            1377
#define IDC_UBER_EMISSIVE_COLOR         1377
#define IDC_UBER_DIFFCOLOR_MUL_S24      1378
#define IDC_UBER_SSS_DIRECTION_MUL_S    1378
#define IDC_UBER_DIFFWEIGHT_MUL28       1379
#define IDC_UBER_SSS_SCATTERAMOUNT_MUL  1379
#define IDC_UBER_DIFFWEIGHT_MUL29       1380
#define IDC_UBER_SSS_DIRECTION_MUL      1380
#define IDC_UBER_DIFFCOLOR_T13          1381
#define IDC_UBER_EMISSIVE_COLOR_T       1381
#define IDC_UBER_DIFFCOLOR_USEMAP12     1382
#define IDC_UBER_SSS_ABSORPTION_USEMAP  1382
#define IDC_UBER_DIFFCOLOR_MUL_S27      1383
#define IDC_UBER_EMISSIVE_COLOR_MUL_S   1383
#define IDC_UBER_DIFFCOLOR_MUL_S26      1384
#define IDC_UBER_SSS_ABSORPTION_DIST_MUL_S 1384
#define IDC_UBER_DIFFWEIGHT_MUL30       1385
#define IDC_UBER_SSS_ABSORPTION_MUL     1385
#define IDC_UBER_DIFFWEIGHT_MUL31       1386
#define IDC_UBER_SSS_ABSORPTION_DIST_MUL 1386
#define IDC_UBER_DIFFCOLOR_USEMAP13     1387
#define IDC_UBER_EMISSIVE_COLOR_USEMAP  1387
#define IDC_UBER_DIFFCOLOR_MUL_S28      1388
#define IDC_UBER_EMISSIVE_WEIGHT_MUL_S  1388
#define IDC_UBER_DIFFWEIGHT_MUL32       1389
#define IDC_UBER_EMISSIVE_COLOR_MUL     1389
#define IDC_UBER_DIFFWEIGHT_MUL33       1390
#define IDC_UBER_EMISSIVE_WEIGHT_MUL    1390
#define IDC_UBER_DIFFCOLOR13            1391
#define IDC_UBER_EMISSIVE_OPACITY       1391
#define IDC_UBER_EMISSIVE_WEIGHT        1391
#define IDC_UBER_DIFFCOLOR_T14          1392
#define IDC_UBER_EMISSIVE_OPACITY_T     1392
#define IDC_UBER_EMISSIVE_WEIGHT_T      1392
#define IDC_UBER_DIFFCOLOR_MUL_S29      1393
#define IDC_UBER_EMISSIVE_OPACITY_MUL_S 1393
#define IDC_UBER_SSS_DIRECTION_T        1393
#define IDC_UBER_DIFFCOLOR_USEMAP14     1394
#define IDC_UBER_EMISSIVE_OPACITY_USEMAP 1394
#define IDC_UBER_EMISSIVE_WEIGHT_USEMAP 1394
#define IDC_UBER_DIFFWEIGHT_MUL34       1395
#define IDC_UBER_EMISSIVE_OPACITY_MUL   1395
#define IDC_UBER_SSS_DIRECTION_USEMAP   1395
#define IDC_CHECK5                      1396
#define IDC_UBER_EMISSIVE_DOUBLESIDED   1396
#define IDC_UBER_DIFFCOLOR14            1397
#define IDC_UBER_MAT_OPACITY            1397
#define IDC_UBER_DIFFCOLOR_T15          1398
#define IDC_UBER_MAT_OPACITY_T          1398
#define IDC_UBER_DIFFCOLOR_MUL_S30      1399
#define IDC_UBER_MAT_OPACITY_MUL_S      1399
#define IDC_UBER_DIFFCOLOR_USEMAP15     1400
#define IDC_UBER_MAT_OPACITY_USEMAP     1400
#define IDC_UBER_DIFFCOLOR_MUL_S31      1401
#define IDC_UBER_MAT_NORMAL_MUL_S       1401
#define IDC_UBER_DIFFWEIGHT_MUL35       1402
#define IDC_UBER_MAT_OPACITY_MUL        1402
#define IDC_UBER_DIFFWEIGHT_MUL36       1403
#define IDC_UBER_MAT_NORMAL_MUL         1403
#define IDC_UBER_DIFFCOLOR15            1404
#define IDC_UBER_MAT_DISPLACE           1404
#define IDC_UBER_DIFFCOLOR_T16          1405
#define IDC_UBER_MAT_DISPLACE_T         1405
#define IDC_UBER_DIFFCOLOR_MUL_S32      1406
#define IDC_UBER_MAT_DISPLACE_MUL_S     1406
#define IDC_UBER_DIFFCOLOR_USEMAP16     1407
#define IDC_UBER_MAT_DISPLACE_USEMAP    1407
#define IDC_UBER_DIFFWEIGHT_MUL37       1408
#define IDC_UBER_MAT_DISPLACE_MUL       1408
#define IDC_UBER_SSS_ABSORPTION_DIST_T  1409
#define IDC_UBER_DIFFCOLOR_T17          1410
#define IDC_UBER_MAT_NORMAL_T           1410
#define IDC_UBER_DIFFCOLOR_USEMAP17     1411
#define IDC_UBER_MAT_NORMAL_USEMAP      1411
#define IDC_UBER_DIFFCOLOR16            1412
#define IDC_UBER_MAT_BUMP               1412
#define IDC_UBER_DIFFCOLOR_T18          1413
#define IDC_UBER_MAT_BUMP_T             1413
#define IDC_UBER_DIFFCOLOR_MUL_S33      1414
#define IDC_UBER_MAT_BUMP_MUL_S         1414
#define IDC_UBER_DIFFCOLOR_USEMAP18     1415
#define IDC_UBER_MAT_BUMP_USEMAP        1415
#define IDC_UBER_DIFFWEIGHT_MUL38       1416
#define IDC_UBER_MAT_BUMP_MUL           1416
#define IDC_UBER_DIFFCOLOR17            1417
#define IDC_UBER_DIFFCOLOR_T19          1418
#define IDC_UBER_DIFFCOLOR_MUL_S34      1419
#define IDC_UBER_DIFFCOLOR_USEMAP19     1420
#define IDC_UBER_SSS_ABSORPTION_DIST_USEMAP 1421
#define IDC_UBER_DIFFWEIGHT_MUL39       1422
#define IDC_UBER_MAT_OPACITY2           1423
#define IDC_UBER_MAT_NORMAL             1423
#define IDC_UBER_DIFFCOLOR19            1430
#define IDC_UBER_DIFFCOLOR_T22          1431
#define IDC_UBER_DIFFCOLOR_MUL_S37      1432
#define IDC_UBER_DIFFCOLOR_USEMAP22     1433
#define IDC_UBER_DIFFWEIGHT_MUL42       1434
#define IDC_COMBO4                      1435
#define IDC_UBER_DIFFUSE_COLOR          1436
#define IDC_UBER_DIFFUSE_COLOR_T        1437
#define IDC_UBER_DIFFUSE_USE            1438
#define IDC_UBER_USE_DIFFUSE            1438
#define IDD_SHADER_CACHE                1439
#define IDD_FIRERENDER_UBERMTL1         1440
#define IDD_FIRERENDER_UBERMTLV2        1441
#define IDD_UBERMTLV2_Z                 1441
#define IDD_UBERMTLV2_BASIC_PARAMS      1441
#define IDD_FIRERENDER_IES_LIGHT_SHADOWS 1442
#define IDD_FIRERENDER_PORTALLIGHT_VOLUME 1443
#define IDD_FIRERENDER_IES_LIGHT_VOLUME 1443
#define IDD_FIRERENDER_IES_GENERAL1     1444
#define IDC_PBR_DIFFUSE_COLOR_MUL_S     1444
#define IDD_UBERMTLV2_DIFFUSE           1444
#define IDD_UBERMTLV2_SSS               1444
#define IDC_PBR_DIFFUSE_COLOR_MAP       1445
#define IDD_UBERMTLV2_ABSORPTION        1445
#define IDC_PBR_DIFFUSE_COLOR_USEMAP    1446
#define IDD_UBERMTLV2_EMISSIVE          1446
#define IDC_PBR_DIFFUSE_COLOR           1447
#define IDD_UBERMTLV2_OVERALL           1447
#define IDC_PBR_DIFFUSE_COLOR_MUL       1448
#define IDD_UBERMTLV2_COATING           1448
#define IDC_PBR_ROUGHNESS_MUL_S         1449
#define IDC_PBR_ROUGHNESS_MAP           1450
#define IDC_PBR_ROUGHNESS_USEMAP        1451
#define IDC_PBR_ROUGHNESS               1452
#define IDC_PBR_ROUGHNESS_MUL           1453
#define IDC_PBR_ROUGHNESS_INVERT        1454
#define IDC_PBR_METALNESS_MUL_S         1455
#define IDC_PBR_METALNESS_MAP           1456
#define IDC_PBR_METALNESS_USEMAP        1457
#define IDC_PBR_METALNESS               1458
#define IDC_PBR_METALNESS_MUL           1459
#define IDC_PBR_CAVITY_MUL_S            1460
#define IDC_PBR_CAVITY_MAP              1461
#define IDC_PBR_CAVITY_USEMAP           1462
#define IDC_PBR_CAVITY                  1463
#define IDC_PBR_CAVITY_MUL              1464
#define IDC_PBR_CAVITY_INVERT           1465
#define IDC_PBR_NORMAL_MUL_S            1466
#define IDC_PBR_NORMAL_MAP              1467
#define IDC_PBR_CAVITY_USEMAP2          1468
#define IDC_PBR_NORMAL_USEMAP           1468
#define IDC_PBR_NORMAL                  1469
#define IDC_PBR_NORMAL_MUL              1470
#define IDC_PBR_OPACITY_MUL_S           1471
#define IDC_PBR_OPACITY_MAP             1472
#define IDC_PBR_OPACITY_USEMAP          1473
#define IDC_PBR_CAVITY_INVERT2          1474
#define IDC_PBR_OPACITY_INVERT          1474
#define IDC_PBR_OPACITY_MUL             1475
#define IDC_PBR_EMISSIVE_MUL_S          1476
#define IDC_PBR_EMISSIVE_COLOR_MUL_S    1476
#define IDC_PBR_EMISSIVE_MAP            1477
#define IDC_PBR_EMISSIVE_COLOR_MAP      1477
#define IDC_PBR_EMISSIVE_USEMAP         1478
#define IDC_PBR_EMISSIVE_COLOR_USEMAP   1478
#define IDC_PBR_EMISSIVE                1479
#define IDC_PBR_EMISSIVE_COLOR          1479
#define IDC_PBR_EMISSIVE_MUL            1480
#define IDC_PBR_EMISSIVE_COLOR_MUL      1480
#define IDC_PBR_NORMAL2                 1481
#define IDC_PBR_EMISSIVE_WEIGHT_MUL_S   1481
#define IDC_PBR_OPACITY                 1482
#define IDC_SC_DIFFUSE                  1483
#define IDC_PBR_EMISSIVE_WEIGHT_MAP     1483
#define IDC_PBR_EMISSIVE_WEIGHT_USEMAP  1484
#define IDC_PBR_WEIGHT_EMISSIVE         1485
#define IDC_PBR_EMISSIVE_WEIGHT_MUL     1486
#define IDC_PBR_SPECULAR_MUL_S          1487
#define IDC_PBR_SPECULAR_MAP            1488
#define IDC_PBR_SPECULAR_USEMAP         1489
#define IDC_PBR_SPECULAR                1490
#define IDC_PBR_SPECULAR_MUL            1491
#define IDC_PBR_GLASS_S                 1492
#define IDC_PBR_GLASS_MAP               1493
#define IDC_PBR_GLASS_USEMAP            1494
#define IDC_PBR_GLASS                   1495
#define IDC_PBR_GLASS_MUL               1496
#define IDC_PBR_GLASS_IOR_S             1497
#define IDC_PBR_GLASS_IOR_MAP           1498
#define IDC_PBR_GLASS_IOR_USEMAP        1499
#define IDC_FIRERENDER_IES_LIGHT_ENABLED 1500
#define IDC_FIRERENDER_IES_LIGHT_AREA_WIDTH 1501
#define IDC_FIRERENDER_IES_LIGHT_AREA_WIDTH_S 1502
#define IDC_FIRERENDER_IES_LIGHT_ENABLED2 1503
#define IDC_FIRERENDER_PHYS_LIGHT_AREA_LENGTHS_S 1503
#define IDC_FIRERENDER_IES_LIGHT_TARGETED 1504
#define IDC_CUSTOM2                     1505
#define IDC_FIRERENDER_PHYS_LIGHT_AREA_LENGTHS 1505
#define IDC_FIRERENDER_IES_LIGHT_IMPORT 1506
#define IDC_FIRERENDER_IES_LIGHT_INTENSITY 1507
#define IDC_FIRERENDER_IES_LIGHT_DELETE_PROFILE 1508
#define IDC_FIRERENDER_IES_LIGHT_INTENSITY_S 1509
#define IDC_FIRERENDER_IES_LIGHT_TEMPERATURE 1510
#define IDC_FIRERENDER_IES_LIGHT_TEMPERATURE_S 1511
#define IDC_FIRERENDER_IES_LIGHT_COLOR  1512
#define IDC_FIRERENDER_IES_LIGHT_SHADOWS_SOFTNESS 1513
#define IDC_FIRERENDER_IES_LIGHT_SHADOWS_SOFTNESS_S 1514
#define IDC_FIRERENDER_IES_LIGHT_RGB_MODE 1515
#define IDC_RADIO2                      1516
#define IDC_FIRERENDER_IES_LIGHT_KELVIN_MODE 1517
#define IDC_FIRERENDER_IES_LIGHT_ROTATION_X_S 1518
#define IDC_FIRERENDER_IES_LIGHT_ROTATION_X 1519
#define IDC_FIRERENDER_IES_LIGHT_ROTATION_Y_S 1520
#define IDC_FIRERENDER_IES_LIGHT_ROTATION_Y 1521
#define IDC_FIRERENDER_IES_LIGHT_ROTATION_Z_S 1522
#define IDC_FIRERENDER_IES_LIGHT_ROTATION_Z 1523
#define IDD_FIRERENDER_SCMTL            1528
#define IDC_SC_NORMAL_MUL_S             1529
#define IDD_FIRERENDER_COLOURCORRMTL    1529
#define IDC_SC_NORMAL_MAP               1530
#define IDC_SC_NORMAL_USEMAP            1531
#define IDD_FIRERENDER_IES_LIGHT_INTENSITY1 1531
#define IDD_FIRERENDER_PHYS_LIGHT_INTENSITY 1531
#define IDC_SC_NORMAL                   1532
#define IDD_FIRERENDER_PHYS_LIGHT_GENERAL 1532
#define IDC_SC_NORMAL_MUL               1533
#define IDC_SC_DISPLACE_MUL_S           1534
#define IDD_FIRERENDER_PHYS_LIGHT_VOLUME 1534
#define IDC_SC_DISPLACE_MAP             1535
#define IDC_SC_DISPLACE_USEMAP          1536
#define IDD_FIRERENDER_PHYS_LIGHT_SHADOWS 1536
#define IDC_SC_DISPLACE                 1537
#define IDD_FIRERENDER_PHYS_LIGHT_DECAY 1537
#define IDC_SC_DISPLACE_MUL             1538
#define IDD_FIRERENDER_PHYS_LIGHT_AREA  1538
#define IDC_SC_IS_BACKGROUND            1539
#define IDD_FIRERENDER_PHYS_LIGHT_SPOT  1539
#define IDD_MTL_UBERV3_DIFFUSE          1540
#define IDD_MTL_UBERV3_REFLECTION       1541
#define IDD_MTL_UBERV3_REFRACTION       1542
#define IDD_MTL_UBERV3_COATING          1543
#define IDC_SC_SHADOW_COLOR_MUL_S       1544
#define IDD_MTL_UBERV3_EMISSIVE         1544
#define IDC_SC_SHADOW_COLOR_MAP         1545
#define IDD_MTL_UBERV3_SSS              1545
#define IDC_SC_SHADOW_COLOR_USEMAP      1546
#define IDD_MTL_UBERV3_NORMAL           1546
#define IDC_SC_SHADOW_COLOR             1547
#define IDD_MTL_UBERV3_TRANSPARENCY     1547
#define IDC_SC_SHADOW_COLOR_MUL         1548
#define IDD_MTL_UBERV3_DISPLACEMENT     1548
#define IDC_SC_SHADOW_WEIGHT_MUL_S      1549
#define IDC_SC_SHADOW_WEIGHT            1552
#define IDC_SC_SHADOW_WEIGHT_MUL        1553
#define IDC_SC_BACKGROUND_COLOR_MUL_S   1559
#define IDC_SC_BACKGROUND_COLOR_MAP     1560
#define IDC_SC_BACKGROUND_COLOR_USEMAP  1561
#define IDC_SC_BACKGROUND_COLOR         1562
#define IDC_SC_BACKGROUND_COLOR_MUL     1563
#define IDC_SC_BACKGROUND_WEIGHT_MUL_S  1564
#define IDC_SC_BACKGROUND_WEIGHT        1567
#define IDC_SC_BACKGROUND_WEIGHT_MUL    1568
#define IDC_SC_BACKGROUND_ALPHA_MUL_S   1569
#define IDC_SC_BACKGROUND_ALPHA         1572
#define IDC_SC_BACKGROUND_ALPHA_MUL     1573
#define IDC_SC_SHADOW_ALPHA_MUL_S       1574
#define IDC_SC_SHADOW_ALPHA             1577
#define IDC_SC_SHADOW_ALPHA_MUL         1578
#define IDC_PBR_BASE_COLOR_MUL          1580
#define IDC_PBR_BASE_COLOR_MUL_S        1581
#define IDC_PBR_BASE_COLOR              1582
#define IDC_PBR_BASE_COLOR_MAP          1583
#define IDC_PBR_BASE_COLOR_USEMAP       1584
#define IDC_QUALITY_RAY_EPSILON         1585
#define IDC_QUALITY_RAY_EPSILON_S       1586
#define IDC_COLORCOURTEXMAP             1587
#define IDC_COLOURCOR_TEXMAP            1587
#define IDC_COLOURCOR_GAMMA_BOUNDARY    1588
#define IDS_FR_MTL_COLOURCORR           1589
#define IDC_COLOURCORR_ENABLE           1589
#define IDC_COLOURCORR_ENABLE2          1590
#define IDC_COLOURCORR_CUSTGAMMA        1591
#define IDC_COLOURCORR_CUSTGAMMA_S      1592
#define IDC_FIRERENDER_PHYS_LIGHT_ENABLED 1593
#define IDC_FIRERENDER_PHYS_LIGHT_TYPE  1594
#define IDC_FIRERENDER_PHYS_LIGHT_BIDIRECT 1595
#define IDC_FIRERENDER_PHYS_LIGHT_AREA_WIDTH 1596
#define IDC_FIRERENDER_PHYS_LIGHT_SHAPE 1597
#define IDC_FIRERENDER_PHYS_LIGHT_AREA_WIDTH_S 1598
#define IDC_FIRERENDER_PHYS_LIGHT_TARGETED 1599
#define IDC_DENOISER_ENABLE             1600
#define IDC_DENOISER_ML                 1601
#define IDC_DENOISER_BILATERAL          1602
#define IDC_DENOISER_LWR                1603
#define IDC_DENOISER_BILATERAL2         1604
#define IDC_DENOISER_EAW                1605
#define IDC_DENOISER_BILATERAL_RADIUS   1610
#define IDC_DENOISER_BILATERAL_RADIUS_S 1611
#define IDC_DENOISER_LWR_SAMPLES        1612
#define IDC_DENOISER_LWR_SAMPLES_S      1613
#define IDC_DENOISER_LWR_RADIUS         1614
#define IDC_DENOISER_LWR_RADIUS_S       1615
#define IDC_DENOISER_LWR_BANDWIDTH      1616
#define IDC_DENOISER_LWR_BANDWIDTH_S    1617
#define IDC_DENOISER_EAW_COLOR          1618
#define IDC_DENOISER_EAW_COLOR_S        1619
#define IDC_DENOISER_EAW_NORMAL         1620
#define IDC_DENOISER_EAW_NORMAL_S       1621
#define IDC_DENOISER_EAW_DEPTH          1622
#define IDC_FIRERENDER_PHYS_LIGHT_TARGET_DISTANCE 1622
#define IDC_DENOISER_EAW_DEPTH_S        1623
#define IDC_FIRERENDER_PHYS_LIGHT_TARGET_DISTANCE_S 1623
#define IDC_DENOISER_EAW_OBJECTID       1624
#define IDC_FIRERENDER_PHYS_LIGHT_INTENSITY 1624
#define IDC_DENOISER_EAW_COLOR_S4       1625
#define IDC_FIRERENDER_PHYS_LIGHT_INTENSITY_S 1625
#define IDC_DENOISER_EAW_OBJECTID_S     1626
#define IDC_FIRERENDER_PHYS_LIGHT_INTENS_UNITS 1626
#define IDC_FIRERENDER_PHYS_LIGHT_LUM_EFF_S 1627
#define IDC_FIRERENDER_PHYS_LIGHT_LUM_EFF 1628
#define IDC_FIRERENDER_PHYS_LIGHT_COLOUR_MODE 1629
#define IDC_FIRERENDER_PHYS_LIGHT_COLOR 1630
#define IDC_FIRERENDER_PHYS_LIGHT_COLOR_T 1631
#define IDC_FIRERENDER_PHYS_LIGHT_TEMPERATURE 1632
#define IDC_FIRERENDER_PHYS_LIGHT_TEMPERATURE_S 1633
#define IDC_FIRERENDER_PHYS_LIGHT_TEMPERATURE_C 1634
#define IDC_FIRERENDER_PHYS_LIGHT_COLOUR_MAP_ENABLED 1635
#define IDC_FIRERENDER_PHYS_LIGHT_AREA_VISIBLE 1636
#define IDC_FIRERENDER_PHYS_LIGHT_MESH_T 1637
#define IDC_FIRERENDER_PHYS_LIGHT_VISIBLE2 1638
#define IDC_FIRERENDER_PHYS_LIGHT_SPOT_VISIBLE 1639
#define IDC_FIRERENDER_PHYS_LIGHT_INNER_CONE 1640
#define IDC_FIRERENDER_PHYS_LIGHT_DECAY_TYPE 1641
#define IDC_FIRERENDER_PHYS_LIGHT_OUTER_CONE 1642
#define IDC_FIRERENDER_PHYS_LIGHT_FALLOFF_START 1643
#define IDC_FIRERENDER_PHYS_LIGHT_FALLOFF_START_S 1644
#define IDC_FIRERENDER_PHYS_LIGHT_FALLOFF_END_S 1645
#define IDC_FIRERENDER_PHYS_LIGHT_INNER_CONE_S 1646
#define IDC_FIRERENDER_PHYS_LIGHT_OUTER_CONE_S 1647
#define IDC_FIRERENDER_PHYS_LIGHT_SHADOW_SOFTNESS 1648
#define IDC_FIRERENDER_PHYS_LIGHT_SHADOW_SOFTNESS_S 1649
#define IDC_FIRERENDER_PHYS_LIGHT_SHADOW_ENABLED 1650
#define IDC_FIRERENDER_PHYS_LIGHT_SHADOW_TRANS 1651
#define IDC_FIRERENDER_PHYS_LIGHT_SHADOW_TRANS_S 1652
#define IDC_FIRERENDER_PHYS_LIGHT_VOLUME_SCALE 1653
#define IDC_FIRERENDER_PHYS_LIGHT_VOLUME_SCALE_S 1654
#define IDS_PHYS_LIGHT_INTENSITY        1655
#define IDS_PHYS_LIGHT_AREA             1656
#define IDS_PHYS_LIGHT_SPOT             1657
#define IDS_PHYS_LIGHT_DECAY            1658
#define IDS_PHYS_LIGHT_SHADOWS          1659
#define IDS_PHYS_LIGHT_VOLUME           1660
#define IDS_PHYS_LIGHT_GENERAL          1661
#define IDC_FIRERENDER_PHYS_LIGHT_INTENSITYNORM 1662
#define IDC_CPU_NUM_THREADS             1663
#define IDC_CPU_NUM_THREADS_S           1664
#define IDC_AUTOTEST_PROGRESS           1665
#define IDC_FIRERENDER_PHYS_LIGHT_AREA_LENGTHS_L 1666
#define IDC_FIRERENDER_PHYS_LIGHT_AREA_WIDTH_L 1667
#define IDD_FIRERENDER_AMBIENTOCCLUSIONMTL 1668
#define IDC_AO_RADIUS                   1669
#define IDC_AO_RADIUS_S                 1670
#define IDC_AO_SIDE                     1671
#define IDC_AO_COLOR0                   1672
#define IDC_AO_COLOR1                   1673
#define IDC_AO_COLOR0_TEXMAP            1674
#define IDC_AO_COLOR1_TEXMAP            1675
#define IDC_UBER3_DIFFUSE_COLOR         1676
#define IDC_UBER3_DIFFUSE_COLOR_T       1677
#define IDC_UBER3_DIFFUSE_WEIGHT        1678
#define IDC_UBER3_DIFFUSE_WEIGHT_S      1679
#define IDC_UBER3_DIFFUSE_WEIGHT_T      1680
#define IDC_UBER3_DIFFUSE_ROUGHNESS     1681
#define IDC_UBER3_DIFFUSE_ROUGHNESS_S   1682
#define IDC_UBER3_DIFFUSE_ROUGHNESS_T   1683
#define IDC_UBER3_DIFFUSE_BACKSCATTERING_COLOR 1684
#define IDC_UBER3_DIFFUSE_NORMAL_X      1685
#define IDC_UBER3_DIFFUSE_NORMAL_X_S    1686
#define IDC_UBER3_DIFFUSE_NORMAL_Y      1687
#define IDC_UBER3_DIFFUSE_NORMAL_Y_S    1688
#define IDC_UBER3_DIFFUSE_NORMAL_Z      1689
#define IDC_UBER3_DIFFUSE_NORMAL_Z_S    1690
#define IDC_UBER3_DIFFUSE_COLOR_T2      1691
#define IDC_UBER3_DIFFUSE_BACKSCATTERING_COLOR_T 1692
#define IDC_UBER3_REFLECTION_ENABLE     1693
#define IDC_UBER3_DIFFUSE_BACKSCATTERING_WEIGHT_T 1694
#define IDC_UBER3_REFLECTION_COLOR      1695
#define IDC_UBER3_DIFFUSE_NORMAL_T      1696
#define IDC_UBER3_REFLECTION_COLOR_T    1697
#define IDC_UBER3_DIFFUSE_NORMAL_X2     1698
#define IDC_UBER3_REFLECTION_WEIGHT     1699
#define IDC_UBER3_DIFFUSE_BACKSCATTERING_WEIGHT 1700
#define IDC_UBER3_REFLECTION_ANISOTROPY_T 1701
#define IDC_UBER3_DIFFUSE_NORMAL_X_S2   1702
#define IDC_UBER3_DIFFUSE_BACKSCATTERING_WEIGHT_S 1703
#define IDC_UBER3_REFLECTION_ANISOTROPY_ROTATION_T 1704
#define IDC_UBER3_REFLECTION_WEIGHT_S   1705
#define IDC_UBER3_REFLECTION_WEIGHT_T   1706
#define IDC_UBER3_REFLECTION_ROUGHNESS  1707
#define IDC_UBER3_REFLECTION_ROUGHNESS_S 1708
#define IDC_UBER3_REFLECTION_ROUGHNESS_T 1709
#define IDC_UBER3_REFLECTION_ANISOTROPY 1710
#define IDC_UBER3_REFLECTION_ANISOTROPY_S 1711
#define IDC_UBER3_REFLECTION_ANISOTROPY_ROTATION 1712
#define IDC_UBER3_REFLECTION_ANISOTROPY_ROTATION_S 1713
#define IDC_UBER3_REFLECTION_MODE       1714
#define IDC_UBER3_REFLECTION_IOR        1715
#define IDC_UBER3_REFLECTION_IOR_S      1716
#define IDC_UBER3_REFLECTION_METALNESS  1717
#define IDS_MTL_UBERV3_DIFFUSE          1718
#define IDC_UBER3_REFLECTION_METALNESS_S 1719
#define IDS_MTL_UBERV3_REFLECTION       1720
#define IDC_UBER3_REFLECTION_USE_SHADER_NORMAL 1721
#define IDS_MTL_UBERV3_REFRACTION       1722
#define IDC_UBER3_REFLECTION_NORMAL_X   1723
#define IDC_UBER3_REFLECTION_NORMAL_X_S 1724
#define IDS_MTL_UBERV3_COATING          1725
#define IDC_UBER3_REFLECTION_NORMAL_Y   1726
#define IDS_MTL_UBERV3_EMISSIVE         1727
#define IDC_UBER3_REFLECTION_NORMAL_Y_S 1728
#define IDS_MTL_UBERV3_SSS              1729
#define IDC_UBER3_REFLECTION_NORMAL_Z   1730
#define IDS_MTL_UBERV3_SSS2             1731
#define IDS_MTL_UBERV3_NORMAL           1732
#define IDC_UBER3_REFLECTION_NORMAL_Z_S 1733
#define IDS_MTL_UBERV3_TRANSPARENCY     1734
#define IDC_UBER3_REFRACTION_THIN_SURFACE 1735
#define IDC_UBER3_REFLECTION_IOR_T      1736
#define IDS_MTL_UBERV3_DISPLACEMENT     1737
#define IDC_UBER3_REFRACTION_COLOR      1738
#define IDC_UBER3_REFLECTION_METALNESS_T 1739
#define IDS_SUBDIV_ADAPTIVE             1740
#define IDC_UBER3_REFRACTION_COLOR_T    1741
#define IDC_UBER3_REFLECTION_NORMAL_T   1742
#define IDS_SUBDIV_LEVEL                1743
#define IDC_UBER3_REFRACTION_ENABLE     1744
#define IDS_STAMP_RESET_TOOLTIP         1744
#define IDC_UBER3_REFRACTION_WEIGHT     1745
#define IDS_STAMP_HELP_TOOLTIP          1745
#define IDC_UBER3_REFRACTION_WEIGHT_S   1746
#define IDC_UBER3_REFRACTION_WEIGHT_T   1747
#define IDC_UBER3_REFRACTION_ROUGHNESS  1748
#define IDC_UBER3_REFRACTION_ROUGHNESS_S 1749
#define IDS_SAMPLING_TIME_TOOLTIP       1749
#define IDS_SAMPLING_SAMPLES_MIN_TOOLTIP 1750
#define IDC_UBER3_REFRACTION_ROUGHNESS_T 1750
#define IDS_SAMPLING_SAMPLES_MAX_TOOLTIP 1751
#define IDC_UBER3_REFRACTION_IOR        1751
#define IDS_SAMPLING_ADAPTIVE_NOISE_THRESHOLD_TOOLTIP 1752
#define IDC_UBER3_REFRACTION_IOR_S      1752
#define IDS_SAMPLING_CONTEXT_ITERATIONS_TOOLTIP 1753
#define IDC_UBER3_REFRACTION_IOR_T      1753
#define IDC_UBER3_COATING_ENABLE        1754
#define IDC_UBER3_REFRACTION_ABSORPTION_DISTANCE 1755
#define IDC_UBER3_COATING_COLOR         1756
#define IDC_UBER3_REFRACTION_ABSORPTION_DISTANCE_S 1757
#define IDC_UBER3_COATING_COLOR_T       1758
#define IDC_UBER3_REFRACTION_ALLOW_CAUSTICS 1759
#define IDC_UBER3_COATING_WEIGHT        1760
#define IDC_UBER3_REFRACTION_ABSORPTION_DISTANCE_T 1761
#define IDC_UBER3_COATING_WEIGHT_S      1762
#define IDC_UBER3_COATING_WEIGHT_T      1763
#define IDC_UBER3_COATING_ROUGHNESS     1764
#define IDC_UBER3_COATING_ROUGHNESS_S   1765
#define IDC_UBER3_COATING_ROUGHNESS_T   1766
#define IDC_UBER3_COATING_IOR           1767
#define IDC_UBER3_COATING_IOR_S         1768
#define IDC_UBER3_COATING_IOR_T         1769
#define IDC_UBER3_COATING_USE_SHADER_NORMAL 1770
#define IDC_UBER3_COATING_NORMAL_X      1771
#define IDC_UBER3_COATING_NORMAL_X_S    1772
#define IDC_UBER3_COATING_NORMAL_Y      1773
#define IDC_UBER3_COATING_NORMAL_Y_S    1774
#define IDC_UBER3_COATING_NORMAL_Z      1775
#define IDC_UBER3_COATING_NORMAL_Z_S    1776
#define IDC_UBER3_COATING_THICKNESS     1777
#define IDC_UBER3_EMISSIVE_ENABLE       1778
#define IDC_UBER3_COATING_THICKNESS_S   1779
#define IDC_UBER3_EMISSIVE_COLOR        1780
#define IDC_UBER3_COATING_THICKNESS_T   1781
#define IDC_UBER3_EMISSIVE_COLOR_T      1782
#define IDC_UBER3_COATING_TRANSMISSION_COLOR 1783
#define IDC_UBER3_EMISSIVE_WEIGHT       1784
#define IDC_UBER3_COATING_TRANSMISSION_COLOR_T 1785
#define IDC_UBER3_EMISSIVE_WEIGHT_S     1786
#define IDC_UBER3_EMISSIVE_WEIGHT_T     1787
#define IDC_UBER3_COATING_NORMAL_T      1788
#define IDC_UBER3_EMISSIVE_DOUBLE_SIDED 1789
#define IDC_UBER3_SSS_ENABLE            1790
#define IDC_UBER3_EMISSIVE_INTENSITY    1791
#define IDC_UBER3_SSS_WEIGHT            1792
#define IDC_UBER3_EMISSIVE_WEIGHT_S2    1793
#define IDC_UBER3_EMISSIVE_INTENSITY_S  1794
#define IDC_UBER3_SSS_WEIGHT_S          1795
#define IDC_UBER3_SSS_WEIGHT_T          1796
#define IDC_UBER3_SSS_USE_DIFFUSE_COLOR 1797
#define IDC_UBER3_SSS_COLOR             1798
#define IDC_UBER3_SSS_COLOR_T           1799
#define IDC_UBER3_SSS_RADIUS_X          1800
#define IDC_UBER3_SSS_RADIUS_X_S        1801
#define IDC_UBER3_SSS_RADIUS_Y          1802
#define IDC_UBER3_SSS_RADIUS_Y_S        1803
#define IDC_UBER3_SSS_RADIUS_Z          1804
#define IDC_UBER3_SSS_RADIUS_Z_S        1805
#define IDC_UBER3_SSS_DIRECTION_T       1806
#define IDC_UBER3_NORMAL_ENABLE         1807
#define IDC_UBER3_SSS_DIRECTION         1808
#define IDC_UBER3_NORMAL_X              1809
#define IDC_UBER3_SSS_DIRECTION_S       1810
#define IDC_UBER3_NORMAL_X_S            1811
#define IDC_UBER3_SSS_USE_DIFFUSE_COLOR2 1812
#define IDC_UBER3_SSS_MULTIPLE_SCATTERING 1813
#define IDC_UBER3_NORMAL_Y              1814
#define IDC_UBER3_SSS_RADIUS_T          1815
#define IDC_UBER3_NORMAL_Y_S            1816
#define IDC_UBER3_NORMAL_Z              1817
#define IDC_UBER3_NORMAL_Z_S            1818
#define IDC_UBER3_NORMAL_T              1819
#define IDC_UBER3_TRANSPARENCY_ENABLE   1820
#define IDC_UBER3_TRANSPARENCY          1821
#define IDC_UBER3_TRANSPARENCY_S        1822
#define IDC_UBER3_TRANSPARENCY_T        1823
#define IDC_UBER3_DISPLACEMENT_ENABLE   1824
#define IDC_UBER3_DISPLACEMENT_T        1825
#define IDC_UBER3_DISPLACEMENT_MIN      1826
#define IDC_UBER3_DISPLACEMENT_MIN_S    1827
#define IDC_UBER3_DISPLACEMENT_MIN_S2   1829
#define IDC_UBER3_DISPLACEMENT_MAX_S    1830
#define IDC_UBER3_DISPLACEMENT_SUBDIV   1831
#define IDC_UBER3_DISPLACEMENT_SUBDIV_S 1832
#define IDC_UBER3_DISPLACEMENT_SUBDIV_TYPE 1833
#define IDC_UBER3_DISPLACEMENT_CREASE_WEIGHT 1834
#define IDC_UBER3_DISPLACEMENT_CREASE_WEIGHT_S 1835
#define IDC_UBER3_DISPLACEMENT_BOUNDARY_INTEROP_TYPE 1836
#define IDC_UBER3_DISPLACEMENT_SUBDIV_S2 1838
#define IDC_UBER3_REFRACTION_ABSORPTION_DISTANCE_T2 1839
#define IDC_UBER3_REFRACTION_ABSORPTION_COLOR_T 1840
#define IDC_PBR_SSS_RADIUS_Y_S          1841
#define IDC_PBR_SSS_RADIUS_Z            1842
#define IDC_PBR_SSS_RADIUS_Z_S          1843
#define IDC_PBR_SSS_RADIUS_X            1854
#define IDC_UBER3_DISPLACEMENT_MAX      1855
#define IDC_PBR_SSS_RADIUS_X_S          1856
#define IDC_PBR_SSS_RADIUS_Y            1857
#define IDC_PBR_GLASS_IOR               1858
#define IDC_PBR_GLASS_IOR_MUL           1859
#define IDC_PBR_SSS_WEIGHT_S            1860
#define IDC_PBR_SSS_WEIGHT_MAP          1861
#define IDC_PBR_SSS_WEIGHT_USEMAP       1862
#define IDC_PBR_SSS_WEIGHT_MUL          1863
#define IDC_PBR_SSS_WEIGHT              1864
#define IDC_PBR_SSS_COLOR_S             1865
#define IDC_PBR_SSS_COLOR_MAP           1866
#define IDC_PBR_SSS_COLOR_USEMAP        1867
#define IDC_PBR_SSS_COLOR_MUL           1868
#define IDC_PBR_SSS_COLOR               1869
#define IDC_UBER3_DISPLACEMENT_ADAPTIVE 1870
#define IDC_UBER3_DISPLACEMENT_ADAPTIVE_S 1871
#define IDC_UBER3_REFRACTION_USE_SHADER_NORMAL 1872
#define IDC_UBER3_REFRACTION_NORMAL_T   1873
#define IDC_UBER3_REFRACTION_ABSORPTION_COLOR 1874
#define IDC_UBER3_REFRACTION_ABSORPTION_COLOR_S 1875
#define IDC_SAMPLING_ADAPTIVE_NOISE_THRESHOLD 1876
#define IDC_SAMPLING_ADAPTIVE_NOISE_THRESHOLD_S 1877
#define IDC_SAMPLING_CONTEXT_ITERATIONS 1878
#define IDC_SAMPLING_CONTEXT_ITERATIONS_S 1879
#define IDC_SAMPLING_ITERATIONS         1880
#define IDC_RADIO_SINGLE_FRAME          1883
#define IDC_RADIO_SEQUENCE_OF_FRAMES    1884

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        312
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1884
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
